export dd_infile=../files/FDate.dat
../bin/viewfiledate >../files/FDate.dat.txt
export dd_infile=../files/FDate.dat.Y2B.srt
../bin/viewfiledate >../files/FDate.dat.Y2B.srt.txt
export dd_infile=../files/FDate.dat.Y2C.srt
../bin/viewfiledate >../files/FDate.dat.Y2C.srt.txt
export dd_infile=../files/FDate.dat.Y2D.srt
../bin/viewfiledate >../files/FDate.dat.Y2D.srt.txt
export dd_infile=../files/FDate.dat.Y2P.srt
../bin/viewfiledate >../files/FDate.dat.Y2P.srt.txt
export dd_infile=../files/FDate.dat.Y2S.srt
../bin/viewfiledate >../files/FDate.dat.Y2S.srt.txt
export dd_infile=../files/FDate.dat.Y2T2.srt
../bin/viewfiledate >../files/FDate.dat.Y2T2.srt.txt
export dd_infile=../files/FDate.dat.Y2T3.srt
../bin/viewfiledate >../files/FDate.dat.Y2T3.srt.txt
export dd_infile=../files/FDate.dat.Y2T4.srt
../bin/viewfiledate >../files/FDate.dat.Y2T4.srt.txt
export dd_infile=../files/FDate.dat.Y2T5.srt
../bin/viewfiledate >../files/FDate.dat.Y2T5.srt.txt
export dd_infile=../files/FDate.dat.Y2T6.srt
../bin/viewfiledate >../files/FDate.dat.Y2T6.srt.txt
export dd_infile=../files/FDate.dat.Y2T8.srt
../bin/viewfiledate >../files/FDate.dat.Y2T8.srt.txt
export dd_infile=../files/FDate.dat.Y2U.srt
../bin/viewfiledate >../files/FDate.dat.Y2U.srt.txt
export dd_infile=../files/FDate.dat.Y2V.srt
../bin/viewfiledate >../files/FDate.dat.Y2V.srt.txt
export dd_infile=../files/FDate.dat.Y2X.srt
../bin/viewfiledate >../files/FDate.dat.Y2X.srt.txt
export dd_infile=../files/FDate.dat.Y2Y.srt
../bin/viewfiledate >../files/FDate.dat.Y2Y.srt.txt
export dd_infile=../files/FDate.dat.Y2Z.srt
../bin/viewfiledate >../files/FDate.dat.Y2Z.srt.txt
