 set dd_infile=..\files\FDate.dat
..\bin\viewfiledate >..\files\FDate.dat.txt
 set dd_infile=..\files\FDate.dat.Y2B.srt
..\bin\viewfiledate >..\files\FDate.dat.Y2B.srt.txt
 set dd_infile=..\files\FDate.dat.Y2C.srt
..\bin\viewfiledate >..\files\FDate.dat.Y2C.srt.txt
 set dd_infile=..\files\FDate.dat.Y2D.srt
..\bin\viewfiledate >..\files\FDate.dat.Y2D.srt.txt
 set dd_infile=..\files\FDate.dat.Y2P.srt
..\bin\viewfiledate >..\files\FDate.dat.Y2P.srt.txt
 set dd_infile=..\files\FDate.dat.Y2S.srt
..\bin\viewfiledate >..\files\FDate.dat.Y2S.srt.txt
 set dd_infile=..\files\FDate.dat.Y2T2.srt
..\bin\viewfiledate >..\files\FDate.dat.Y2T2.srt.txt
 set dd_infile=..\files\FDate.dat.Y2T3.srt
..\bin\viewfiledate >..\files\FDate.dat.Y2T3.srt.txt
 set dd_infile=..\files\FDate.dat.Y2T4.srt
..\bin\viewfiledate >..\files\FDate.dat.Y2T4.srt.txt
 set dd_infile=..\files\FDate.dat.Y2T5.srt
..\bin\viewfiledate >..\files\FDate.dat.Y2T5.srt.txt
 set dd_infile=..\files\FDate.dat.Y2T6.srt
..\bin\viewfiledate >..\files\FDate.dat.Y2T6.srt.txt
 set dd_infile=..\files\FDate.dat.Y2T8.srt
..\bin\viewfiledate >..\files\FDate.dat.Y2T8.srt.txt
 set dd_infile=..\files\FDate.dat.Y2U.srt
..\bin\viewfiledate >..\files\FDate.dat.Y2U.srt.txt
 set dd_infile=..\files\FDate.dat.Y2V.srt
..\bin\viewfiledate >..\files\FDate.dat.Y2V.srt.txt
 set dd_infile=..\files\FDate.dat.Y2X.srt
..\bin\viewfiledate >..\files\FDate.dat.Y2X.srt.txt
 set dd_infile=..\files\FDate.dat.Y2Y.srt
..\bin\viewfiledate >..\files\FDate.dat.Y2Y.srt.txt
 set dd_infile=..\files\FDate.dat.Y2Z.srt
..\bin\viewfiledate >..\files\FDate.dat.Y2Z.srt.txt
