diff   ../files/FDate.dat.Y2T8.srt ../files/FDate.dat.Y2T6.srt
diff   ../files/FDate.dat.Y2T4.srt ../files/FDate.dat.Y2T6.srt
diff   ../files/FDate.dat.Y2T2.srt ../files/FDate.dat.Y2T6.srt
diff   ../files/FDate.dat.Y2T3.srt ../files/FDate.dat.Y2T6.srt
diff   ../files/FDate.dat.Y2T5.srt ../files/FDate.dat.Y2T6.srt
diff   ../files/FDate.dat.Y2T6.srt ../files/FDate.dat.Y2T6.srt
diff   ../files/FDate.dat.Y4T7.srt ../files/FDate.dat.Y2T6.srt
diff   ../files/FDate.dat.Y2B.srt  ../files/FDate.dat.Y2T6.srt
diff   ../files/FDate.dat.Y2C.srt  ../files/FDate.dat.Y2T6.srt
diff   ../files/FDate.dat.Y2D.srt  ../files/FDate.dat.Y2T6.srt
diff   ../files/FDate.dat.Y2P.srt  ../files/FDate.dat.Y2T6.srt
diff   ../files/FDate.dat.Y2S.srt  ../files/FDate.dat.Y2T6.srt
diff   ../files/FDate.dat.Y2U.srt  ../files/FDate.dat.Y2T6.srt
diff   ../files/FDate.dat.Y2V.srt  ../files/FDate.dat.Y2T6.srt
diff   ../files/FDate.dat.Y2X.srt  ../files/FDate.dat.Y2T6.srt
diff   ../files/FDate.dat.Y2X.srt  ../files/FDate.dat.Y2T6.srt
diff   ../files/FDate.dat.Y2Y.srt  ../files/FDate.dat.Y2T6.srt
diff   ../files/FDate.dat.Y2Z.srt  ../files/FDate.dat.Y2T6.srt