comp /M /A C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y2T8.srt C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y2T6.srt
comp /M /A C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y2T4.srt C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y2T6.srt
comp /M /A C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y2T2.srt C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y2T6.srt
comp /M /A C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y2T3.srt C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y2T6.srt
comp /M /A C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y2T5.srt C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y2T6.srt
comp /M /A C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y2T6.srt C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y2T6.srt
comp /M /A C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y4T7.srt C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y2T6.srt
comp /M /A C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y2B.srt  C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y2T6.srt
comp /M /A C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y2C.srt  C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y2T6.srt
comp /M /A C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y2D.srt  C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y2T6.srt
comp /M /A C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y2P.srt  C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y2T6.srt
comp /M /A C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y2S.srt  C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y2T6.srt
comp /M /A C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y2U.srt  C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y2T6.srt
comp /M /A C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y2V.srt  C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y2T6.srt
comp /M /A C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y2X.srt  C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y2T6.srt
comp /M /A C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y2X.srt  C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y2T6.srt
comp /M /A C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y2Y.srt  C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y2T6.srt
comp /M /A C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y2Z.srt  C:\GCSORT\GCSORT_relnew\tests\files\FDate.dat.Y2T6.srt