# for cygwin
# htdocs=/srv/www/htdocs
htdocs=/var/www/vhosts/wortfee.net/httpdocs

all:	p001_wortfee_img

p001_wortfee_img:
# images
	cp p001_wortfee_name.png $(htdocs)/img/p001_wortfee_name.png
	cp p001_wortfee_slide1.jpg $(htdocs)/img/p001_wortfee_slide1.jpg
	cp p001_wortfee_slide2.jpg $(htdocs)/img/p001_wortfee_slide2.jpg
	cp p001_wortfee_lang_DE.png $(htdocs)/img/p001_wortfee_lang_DE.png
	cp p001_wortfee_lang_EN.png $(htdocs)/img/p001_wortfee_lang_EN.png
	cp p001_wortfee_lang_HU.png $(htdocs)/img/p001_wortfee_lang_HU.png
	
clean:
# images
	rm -f $(htdocs)/img/p001_wortfee_name.png
	rm -f $(htdocs)/img/p001_wortfee_slide1.jpg
	rm -f $(htdocs)/img/p001_wortfee_slide2.jpg
	rm -f $(htdocs)/img/p001_wortfee_lang_DE.png
	rm -f $(htdocs)/img/p001_wortfee_lang_EN.png
	rm -f $(htdocs)/img/p001_wortfee_lang_HU.png
    