# compile htm2cob
all:	htm2cob

htm2cob:	htm2cob.cob  htm2cob0.cpy htm2cob1.cpy htm2cob2.cpy \
			htm2cob3.cpy htm2cob4.cpy htm2cob5.cpy htm2cob6.cpy \
			htm2cob7.cpy htm2cob8.cpy
			cobc -x -free -W htm2cob.cob

clean:
	rm -f htm2cob
