# for cygwin
# htdocs=/srv/www/htdocs
# for linux
htdocs=/var/www/vhosts/wortfee.net/httpdocs

all:	p001_wortfee_css

p001_wortfee_css:
# css
	cp w3.css $(htdocs)/css/w3.css
	cp jquery.countdown.css $(htdocs)/css/jquery.countdown.css
	
clean:
# css
	rm -f $(htdocs)/css/w3.css
	rm -f $(htdocs)/css/jquery.countdown.css
