#line 2 "scanner.c"

#line 4 "scanner.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */

/* %if-c-only */
/* %if-not-reentrant */

/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
/* %endif */

/* %if-c-only */
    
/* %endif */

/* %if-c-only */

/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* %if-c++-only */
/* %endif */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* %not-for-header */

/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

/* %if-not-reentrant */
extern yy_size_t yyleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
extern FILE *yyin, *yyout;
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
	FILE *yy_input_file;
/* %endif */

/* %if-c++-only */
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

/* %if-not-reentrant */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */

/* %if-not-reentrant */
/* %not-for-header */

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;
/* %ok-for-header */

/* %endif */

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

/* %endif */

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */

#define yywrap() 1
#define YY_SKIP_YYWRAP

#define FLEX_DEBUG

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

/* %if-c-only Standard (non-C++) definition */

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;

/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 55
#define YY_END_OF_BUFFER 56
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[376] =
    {   0,
       52,   52,   56,   54,   53,   55,   54,   54,   54,   54,
       52,   39,   38,   52,   50,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   50,   52,   50,   53,
        0,   51,    0,    0,   51,   48,    0,   40,    0,    0,
        0,    0,    0,    0,    0,   52,   39,   49,   52,   49,
       52,   52,   52,   49,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   49,   52,   52,   52,   52,   52,
       52,   52,   52,   49,   51,   51,   48,    0,    0,   40,
        0,    0,    0,    0,    0,    0,   39,   52,   52,   52,
       27,   52,   52,   52,   52,   52,   52,   52,   52,   52,

       52,   52,   52,   52,   52,   14,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   10,    1,   52,    0,   43,
        0,   40,    0,    0,    0,    0,    0,   37,    0,   39,
       52,   13,   52,   16,   52,   52,   52,   52,   52,   52,
        2,   52,   52,   52,   52,   52,   15,   12,   52,   52,
       52,   52,   52,   52,   23,   52,    3,   52,   52,   52,
        0,   40,    0,   36,    0,    0,    0,    0,   39,    6,
       52,   52,   52,   52,   20,   52,   52,   52,    9,   52,
        4,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   40,    0,    0,    0,    0,   41,   52,   22,

       32,    5,   19,   17,   52,   52,   52,   24,   18,    8,
        7,   52,   47,   52,   52,   52,   52,   42,    0,   33,
        0,    0,   41,   30,   11,   52,   52,   52,   25,   52,
       26,    0,   52,   42,   31,    0,    0,   41,   52,   34,
       28,   21,    0,   52,   42,   35,   29,   41,   52,    0,
       52,   42,   41,   52,    0,   52,   42,   41,   52,    0,
       52,   42,   41,   52,    0,   52,   42,   41,    0,   52,
        0,   52,   42,   41,    0,   52,    0,    0,   52,   42,
       41,    0,   52,    0,    0,   42,   41,    0,   52,    0,
        0,   42,   41,    0,   52,   46,    0,   42,   41,    0,

       52,    0,   42,   41,    0,   52,    0,   42,   41,    0,
        0,   42,   41,    0,    0,   42,   41,    0,    0,   42,
       41,    0,    0,   42,   41,    0,    0,   42,   41,    0,
        0,   42,   41,    0,    0,   42,   41,    0,    0,   42,
       41,    0,    0,   42,   41,    0,    0,   42,   41,    0,
        0,   42,   41,    0,    0,   42,   41,    0,    0,   42,
        0,    0,    0,    0,    0,   44,    0,    0,    0,    0,
        0,    0,    0,   45,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    4,    4,    4,    4,    6,    7,
        7,    8,    9,   10,   11,   12,    7,   13,   14,   15,
       16,   16,   16,   16,   16,   16,   16,    4,   17,    1,
       18,    1,    1,    1,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   28,   41,   42,   43,
        4,    1,    4,    1,   28,    1,   44,   45,   46,   47,

       48,   49,   50,   51,   52,   28,   53,   54,   55,   56,
       57,   58,   59,   60,   61,   62,   63,   64,   28,   65,
       66,   67,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[68] =
    {   0,
        1,    1,    2,    3,    1,    3,    4,    5,    5,    4,
        5,    6,    6,    6,    6,    7,    3,    5,    7,    7,
        7,    7,    6,    7,    7,    7,    7,    7,    7,    6,
        7,    6,    7,    7,    7,    6,    6,    6,    7,    7,
        6,    6,    7,    7,    7,    7,    7,    6,    7,    7,
        7,    7,    7,    6,    7,    6,    7,    7,    7,    6,
        6,    6,    7,    7,    6,    6,    7
    } ;

static yyconst flex_int16_t yy_base[386] =
    {   0,
        0,    0,  352, 1061,   66, 1061,  332,   72,   71,   89,
        0,   79,    0,   61,   72,   71,   82,   44,   70,   84,
       71,  116,   89,   93,  124,   81,    0,   78,  109,   95,
      303,    0,  299,  187,  290,  289,  205,  145,  198,  108,
      115,  116,  121,  165,  176,    0,  169,    0,  175,    0,
      187,  181,  181,  203,  210,  196,  194,  214,  210,  215,
      209,  201,  223,  202,    0,  238,  213,  239,  232,  253,
      244,  255,  250,    0, 1061,    0, 1061,  310,  163,  274,
      259,  251,  246,  276,  228,  270,  316,  272,  300,  282,
      297,  315,  306,  314,  308,  310,  319,  314,  322,  325,

      324,  327,  328,  315,  327,    0,  337,  323,  325,  327,
      346,  338,  340,  345,  349,    0,    0,  344,  381, 1061,
      405,  403,  333,  349,  376,  376,  390, 1061,  368,  413,
      384,    0,  387,    0,  391,  391,  401,  393,  409,  414,
        0,  397,  413,  403,  415,  402,    0,    0,  408,  415,
      420,  410,  407,  413,    0,  414,    0,  413,  425,  433,
      472,  470,  470, 1061,  433,  436,  449,  448,  478,    0,
      459,  475,  461,  462,    0,  463,  463,  480,    0,  462,
        0,  486,  475,  478,  488,  488,  490,  483,  493,  482,
      496,  496,  533,  493,  496,  517,  514,  550,  505,    0,

        0,    0,    0,    0,  521,  509,  525,    0,    0,    0,
        0,  533,    0,  534,  533,  520,  582,  557,  536, 1061,
      533,  555,  581,    0,    0,  536,  573,  583,    0,  584,
        0,  570,  571,  596, 1061,  583,  593,  602,  589,    0,
        0,    0,  582,  583,  609, 1061, 1061,  620,  586,  592,
      602,  633,  640,  621,  614,  615,  644,  655,  621,  629,
      631,  663,  667,  687,  649,  659,  687,  697,  653,  669,
      276,  724,  702,  706,  686,  687,  264,  695,  261,  730,
      754,  691,  692,  254,  738,  760,  778,  731,  736,  235,
      699,  782,  786,  708,  723, 1061,  751,  793,  797,  778,

      779,  781,  802,  806,  239,  208,  802,  811,  817,  792,
      798,  826,  830,  794,  799,  836,  840,  809,  821,  849,
      853,  847,  842,  860,  864,  841,  860,  871,  875,  854,
      861,  884,  888,  880,  863,  896,  906,  156,  865,  910,
      919,  876,  876,  930,  934,  877,  904,  940,  944,  904,
      900,  953,  957,  921,  923,  963,    0,  939,  154, 1061,
      942,  105,  938,  100,  939, 1061,  944,  940,  942,  946,
       88,   55,   52, 1061, 1061, 1008, 1010, 1012, 1019, 1026,
     1031, 1036, 1043, 1050, 1054
    } ;

static yyconst flex_int16_t yy_def[386] =
    {   0,
      375,    1,  375,  375,  375,  375,  375,  376,  375,  375,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  375,
      375,  378,  379,  380,  379,  375,  376,  375,  375,  375,
      375,  375,  375,  375,  375,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  375,  378,  375,  380,  381,  375,
      375,  375,  375,  375,  375,  375,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,

      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  382,  375,
      381,  375,  375,  375,  375,  375,  375,  375,  375,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      382,  375,  375,  375,  375,  375,  375,  375,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  375,  375,  375,  375,  375,  377,  377,  377,

      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  383,  375,  375,  375,
      375,  375,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  375,  377,  375,  375,  375,  375,  377,  377,  377,
      377,  377,  375,  377,  375,  375,  375,  377,  377,  375,
      377,  375,  377,  377,  375,  377,  375,  377,  377,  375,
      377,  375,  377,  384,  375,  377,  375,  377,  375,  377,
      385,  377,  375,  377,  375,  377,  375,  375,  377,  375,
      377,  375,  377,  375,  375,  375,  377,  375,  377,  375,
      375,  375,  377,  375,  377,  375,  375,  375,  377,  375,

      377,  375,  375,  377,  375,  377,  375,  375,  377,  375,
      375,  375,  377,  375,  375,  375,  377,  375,  375,  375,
      377,  375,  375,  375,  377,  375,  375,  375,  377,  375,
      375,  375,  377,  375,  375,  375,  377,  375,  375,  375,
      377,  375,  375,  375,  377,  375,  375,  375,  377,  375,
      375,  375,  377,  375,  375,  375,  377,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,    0,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375
    } ;

static yyconst flex_int16_t yy_nxt[1129] =
    {   0,
        4,    5,    6,    4,    7,    8,    4,    4,    9,   10,
        9,   11,   12,   12,   12,   12,    4,    4,   13,   14,
       15,   13,   16,   17,   18,   11,   19,   11,   11,   11,
       20,   21,   22,   23,   11,   24,   25,   11,   26,   11,
       27,   28,   29,   13,   14,   15,   13,   16,   17,   18,
       11,   19,   11,   11,   20,   21,   22,   23,   11,   24,
       25,   11,   26,   11,   27,   28,   29,   30,  374,  373,
       57,   31,   33,   33,   33,   34,   35,   36,   34,   33,
       33,   34,   33,   38,   38,   38,   38,   48,   34,   33,
       39,   47,   47,   47,   47,   57,   30,   50,  372,   49,

       31,   58,   52,   60,   51,   53,   59,   40,   54,   41,
       65,   42,   48,   55,   56,   66,  366,   72,  364,   73,
       43,   44,   50,   49,   45,   58,   52,   60,   51,   53,
       74,   59,   40,   54,   41,   65,   42,   55,   56,   81,
       66,   72,   67,   73,   43,   44,   61,   82,   45,   62,
       83,   63,   68,   84,   64,   74,   69,   80,   80,   80,
       80,   70,   71,   81,  362,  342,  119,   67,  120,  119,
       61,   82,  119,   62,   83,   63,   68,   84,   64,  119,
       69,   87,   87,   87,   87,   70,   71,   33,   33,   33,
       34,   33,   36,   34,   33,   33,   34,   33,   86,   39,

       85,   88,   91,   34,   33,   33,   33,   33,   34,   33,
       36,   34,   33,   33,   34,   33,   40,  310,   89,   92,
       90,   34,   33,   86,   85,   93,   88,   91,   95,  127,
       44,   96,   94,   97,   98,  104,  102,  128,  105,  107,
      100,   40,   89,   92,   90,  101,  103,  106,  310,   99,
       93,  296,  111,   95,   44,   96,   94,   97,  108,   98,
      104,  102,  105,  107,  100,  112,  290,  113,  109,  101,
      103,  114,  106,   99,  116,  110,  111,  117,  284,  118,
      123,  284,  124,  108,  125,  115,  122,  122,  122,  122,
      112,  113,  109,  278,   79,   77,  114,  126,  116,  110,

      129,  131,  117,  118,   77,  123,  124,   75,  125,  115,
       33,   33,   33,   33,   33,   36,   33,   33,   33,   33,
       33,  132,  126,  134,  129,  131,   33,   33,  130,  130,
      130,  130,  135,  136,  163,  137,  138,   32,  139,  133,
      140,  141,  164,  142,  143,  144,  132,  134,  145,  146,
      147,  375,  148,  149,  375,  152,  135,  153,  136,  137,
      150,  138,  139,  133,  140,  154,  141,  142,  155,  143,
      144,  156,  151,  145,  146,  147,  148,  157,  149,  152,
      158,  153,  159,  160,  119,  150,  120,  119,  165,  154,
      119,  127,  375,  155,  166,  156,  151,  119,  167,  128,

      168,  157,  375,  375,  158,  170,  159,  160,  119,  171,
      120,  119,  165,  172,  119,  162,  162,  162,  162,  166,
      173,  119,  174,  167,  168,  169,  169,  169,  169,  175,
      170,  176,  177,  179,  171,  178,  180,  181,  172,  182,
      183,  184,  185,  191,  173,  186,  187,  174,  188,  189,
      190,  192,  375,  175,  375,  194,  176,  177,  179,  178,
      180,  375,  181,  182,  183,  195,  184,  185,  191,  186,
      187,  163,  188,  189,  190,  375,  192,  120,  375,  164,
      194,  375,  193,  193,  193,  193,  196,  197,  375,  195,
      198,  198,  198,  198,  199,  200,  375,  201,  202,  203,

      204,  205,  375,  206,  207,  375,  208,  209,  210,  211,
      196,  197,  212,  375,  213,  214,  375,  215,  199,  216,
      200,  201,  202,  203,  204,  217,  205,  206,  219,  207,
      208,  209,  220,  210,  211,  221,  222,  212,  213,  375,
      214,  215,  224,  225,  216,  218,  218,  218,  218,  217,
      226,  227,  219,  228,  229,  230,  220,  231,  375,  236,
      221,  222,  223,  223,  223,  223,  224,  375,  225,  234,
      234,  234,  234,  235,  226,  237,  227,  239,  228,  229,
      230,  231,  232,  232,  236,  232,  232,  232,  232,  232,
      232,  232,  232,  238,  238,  238,  238,  235,  232,  232,

      237,  239,  240,  241,  242,  375,  243,  244,  245,  245,
      245,  245,  246,  247,  248,  248,  248,  248,  249,  250,
      251,  252,  252,  252,  252,  254,  240,  255,  241,  242,
      243,  244,  253,  253,  253,  253,  246,  256,  247,  259,
      260,  261,  249,  250,  251,  257,  257,  257,  257,  254,
      264,  255,  258,  258,  258,  258,  262,  262,  262,  262,
      265,  256,  266,  375,  259,  260,  261,  263,  263,  263,
      263,  375,  375,  271,  264,  267,  267,  267,  267,  268,
      268,  268,  268,  272,  265,  375,  266,  269,  269,  275,
      269,  269,  269,  269,  269,  269,  269,  269,  271,  273,

      273,  273,  273,  269,  269,  276,  375,  375,  272,  274,
      274,  274,  274,  275,  280,  280,  280,  280,  281,  281,
      281,  281,  375,  282,  283,  285,  288,  289,  297,  276,
      277,  277,  277,  277,  277,  279,  279,  279,  279,  300,
      375,  278,  286,  286,  286,  286,  279,  282,  283,  285,
      288,  289,  297,  279,  301,  279,  291,  294,  375,  279,
      279,  279,  295,  300,  279,  279,  287,  287,  287,  287,
      375,  279,  292,  292,  292,  292,  375,  279,  301,  279,
      302,  291,  294,  279,  279,  279,  375,  295,  279,  279,
      293,  293,  293,  293,  298,  298,  298,  298,  299,  299,

      299,  299,  305,  306,  302,  303,  303,  303,  303,  304,
      304,  304,  304,  307,  308,  308,  308,  308,  309,  309,
      309,  309,  311,  312,  312,  312,  312,  305,  306,  313,
      313,  313,  313,  314,  315,  318,  319,  307,  316,  316,
      316,  316,  317,  317,  317,  317,  322,  311,  320,  320,
      320,  320,  321,  321,  321,  321,  323,  314,  315,  318,
      319,  324,  324,  324,  324,  325,  325,  325,  325,  326,
      322,  327,  328,  328,  328,  328,  329,  329,  329,  329,
      323,  330,  331,  332,  332,  332,  332,  333,  333,  333,
      333,  334,  335,  338,  326,  327,  336,  336,  336,  336,

      337,  337,  337,  337,  339,  330,  343,  331,  340,  340,
      340,  340,  346,  347,  350,  334,  335,  334,  341,  341,
      341,  341,  344,  344,  344,  344,  351,  375,  339,  375,
      343,  345,  345,  345,  345,  375,  346,  347,  350,  354,
      355,  334,  348,  348,  348,  348,  349,  349,  349,  349,
      358,  351,  352,  352,  352,  352,  353,  353,  353,  353,
      359,  361,  369,  354,  355,  356,  356,  356,  356,  357,
      357,  357,  357,  363,  358,  360,  360,  360,  360,  365,
      367,  368,  370,  371,  359,  375,  361,  369,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  363,  375,  375,

      375,  375,  375,  365,  367,  368,  370,  371,   37,   37,
       37,   37,   37,   37,   37,   46,   46,   76,   76,   33,
       33,   33,   33,   33,   33,   33,   78,   78,   78,   78,
       78,   78,   78,  121,  121,  375,  121,  121,  161,  161,
      375,  161,  161,  233,  375,  233,  233,  233,  233,  233,
      270,  375,  270,  270,  270,  270,  270,  277,  277,  277,
        3,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,

      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375
    } ;

static yyconst flex_int16_t yy_chk[1129] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    5,  373,  372,
       18,    5,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    9,    9,    9,    9,   14,    8,    8,
       10,   12,   12,   12,   12,   18,   30,   15,  371,   14,

       30,   19,   16,   21,   15,   16,   20,   10,   17,   10,
       23,   10,   14,   17,   17,   24,  364,   26,  362,   28,
       10,   10,   15,   14,   10,   19,   16,   21,   15,   16,
       29,   20,   10,   17,   10,   23,   10,   17,   17,   40,
       24,   26,   25,   28,   10,   10,   22,   41,   10,   22,
       42,   22,   25,   43,   22,   29,   25,   38,   38,   38,
       38,   25,   25,   40,  359,  338,   79,   25,   79,   79,
       22,   41,   79,   22,   42,   22,   25,   43,   22,   79,
       25,   47,   47,   47,   47,   25,   25,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   45,   39,

       44,   49,   52,   34,   34,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   39,  306,   51,   53,
       51,   37,   37,   45,   44,   54,   49,   52,   55,   85,
       39,   56,   54,   57,   58,   61,   60,   85,   62,   64,
       59,   39,   51,   53,   51,   59,   60,   63,  305,   58,
       54,  290,   67,   55,   39,   56,   54,   57,   66,   58,
       61,   60,   62,   64,   59,   68,  284,   69,   66,   59,
       60,   70,   63,   58,   71,   66,   67,   72,  279,   73,
       81,  277,   82,   66,   83,   70,   80,   80,   80,   80,
       68,   69,   66,  271,   36,   35,   70,   84,   71,   66,

       86,   88,   72,   73,   33,   81,   82,   31,   83,   70,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   89,   84,   90,   86,   88,   78,   78,   87,   87,
       87,   87,   91,   92,  123,   93,   94,    7,   95,   89,
       96,   97,  123,   98,   99,  100,   89,   90,  101,  102,
      103,    3,  104,  105,    0,  108,   91,  109,   92,   93,
      107,   94,   95,   89,   96,  110,   97,   98,  111,   99,
      100,  112,  107,  101,  102,  103,  104,  113,  105,  108,
      114,  109,  115,  118,  119,  107,  119,  119,  124,  110,
      119,  127,    0,  111,  125,  112,  107,  119,  126,  127,

      129,  113,    0,    0,  114,  131,  115,  118,  121,  133,
      121,  121,  124,  135,  121,  122,  122,  122,  122,  125,
      136,  121,  137,  126,  129,  130,  130,  130,  130,  138,
      131,  139,  140,  143,  133,  142,  144,  145,  135,  146,
      149,  150,  151,  159,  136,  152,  153,  137,  154,  156,
      158,  160,    0,  138,    0,  165,  139,  140,  143,  142,
      144,    0,  145,  146,  149,  166,  150,  151,  159,  152,
      153,  163,  154,  156,  158,  161,  160,  161,  161,  163,
      165,  161,  162,  162,  162,  162,  167,  168,  161,  166,
      169,  169,  169,  169,  171,  172,    0,  173,  174,  176,

      177,  178,    0,  180,  182,    0,  183,  184,  185,  186,
      167,  168,  187,    0,  188,  189,    0,  190,  171,  191,
      172,  173,  174,  176,  177,  192,  178,  180,  194,  182,
      183,  184,  195,  185,  186,  196,  197,  187,  188,    0,
      189,  190,  199,  205,  191,  193,  193,  193,  193,  192,
      206,  207,  194,  212,  214,  215,  195,  216,    0,  221,
      196,  197,  198,  198,  198,  198,  199,    0,  205,  218,
      218,  218,  218,  219,  206,  222,  207,  226,  212,  214,
      215,  216,  217,  217,  221,  217,  217,  217,  217,  217,
      217,  217,  217,  223,  223,  223,  223,  219,  217,  217,

      222,  226,  227,  228,  230,    0,  232,  233,  234,  234,
      234,  234,  236,  237,  238,  238,  238,  238,  239,  243,
      244,  245,  245,  245,  245,  249,  227,  250,  228,  230,
      232,  233,  248,  248,  248,  248,  236,  251,  237,  254,
      255,  256,  239,  243,  244,  252,  252,  252,  252,  249,
      259,  250,  253,  253,  253,  253,  257,  257,  257,  257,
      260,  251,  261,    0,  254,  255,  256,  258,  258,  258,
      258,    0,    0,  265,  259,  262,  262,  262,  262,  263,
      263,  263,  263,  266,  260,    0,  261,  264,  264,  269,
      264,  264,  264,  264,  264,  264,  264,  264,  265,  267,

      267,  267,  267,  264,  264,  270,    0,    0,  266,  268,
      268,  268,  268,  269,  273,  273,  273,  273,  274,  274,
      274,  274,    0,  275,  276,  278,  282,  283,  291,  270,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  294,
        0,  272,  280,  280,  280,  280,  272,  275,  276,  278,
      282,  283,  291,  272,  295,  272,  285,  288,    0,  272,
      272,  272,  289,  294,  272,  272,  281,  281,  281,  281,
        0,  272,  286,  286,  286,  286,    0,  272,  295,  272,
      297,  285,  288,  272,  272,  272,    0,  289,  272,  272,
      287,  287,  287,  287,  292,  292,  292,  292,  293,  293,

      293,  293,  300,  301,  297,  298,  298,  298,  298,  299,
      299,  299,  299,  302,  303,  303,  303,  303,  304,  304,
      304,  304,  307,  308,  308,  308,  308,  300,  301,  309,
      309,  309,  309,  310,  311,  314,  315,  302,  312,  312,
      312,  312,  313,  313,  313,  313,  318,  307,  316,  316,
      316,  316,  317,  317,  317,  317,  319,  310,  311,  314,
      315,  320,  320,  320,  320,  321,  321,  321,  321,  322,
      318,  323,  324,  324,  324,  324,  325,  325,  325,  325,
      319,  326,  327,  328,  328,  328,  328,  329,  329,  329,
      329,  330,  331,  334,  322,  323,  332,  332,  332,  332,

      333,  333,  333,  333,  335,  326,  339,  327,  336,  336,
      336,  336,  342,  343,  346,  330,  331,  334,  337,  337,
      337,  337,  340,  340,  340,  340,  347,    0,  335,    0,
      339,  341,  341,  341,  341,    0,  342,  343,  346,  350,
      351,  334,  344,  344,  344,  344,  345,  345,  345,  345,
      354,  347,  348,  348,  348,  348,  349,  349,  349,  349,
      355,  358,  368,  350,  351,  352,  352,  352,  352,  353,
      353,  353,  353,  361,  354,  356,  356,  356,  356,  363,
      365,  367,  369,  370,  355,    0,  358,  368,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  361,    0,    0,

        0,    0,    0,  363,  365,  367,  369,  370,  376,  376,
      376,  376,  376,  376,  376,  377,  377,  378,  378,  379,
      379,  379,  379,  379,  379,  379,  380,  380,  380,  380,
      380,  380,  380,  381,  381,    0,  381,  381,  382,  382,
        0,  382,  382,  383,    0,  383,  383,  383,  383,  383,
      384,    0,  384,  384,  384,  384,  384,  385,  385,  385,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,

      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 1;

static yyconst flex_int16_t yy_rule_linenum[55] =
    {   0,
       61,   62,   63,   64,   65,   66,   67,   68,   69,   70,
       71,   72,   73,   74,   75,   76,   77,   78,   79,   80,
       81,   82,   83,   84,   85,   86,   88,   89,   90,   91,
       92,   93,   94,   95,   96,   99,  100,  103,  104,  105,
      106,  107,  112,  114,  115,  116,  117,  120,  126,  127,
      128,  129,  130,  131
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
/*
 *  Copyright (C) 2009 Cedric ISSALY
 *  Copyright (C) 2016 Sauro Menna
 *
 *	This file is part of OCSort.
 *
 *  OCSort is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  OCSort is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with OCSort.  If not, see <http://www.gnu.org/licenses/>.

*/
#line 22 "scanner.l"
  #include <stdio.h>
  #include <stdlib.h>
  #ifndef _MSC_VER
	  #define _strdup strdup
	  #include "utils.h"
	  #define xstrtoll   strtoll
  #else
	  #include <io.h>
	  #define isatty _isatty
	  #define fileno _fileno
	  #define xstrtoll    _strtoi64
  #endif
  #include "parser.h"
  char * pEnd;
  void yyerror(const char *error) {
	printf("Error : %s\n",error);
	if(yytext != NULL)
		printf("Error near element : %s\n", yytext);
} 
#define YY_NO_INPUT
#line 962 "scanner.c"

#define INITIAL 0

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */

static int yy_init_globals (void );

/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* %if-bison-bridge */
/* %endif */

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

/* %not-for-header */

/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */

/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\
/* %if-c++-only C++ definition \ */\
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */

/* %ok-for-header */

/* %not-for-header */

/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */

extern int yylex (void);

#define YY_DECL int yylex (void)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %not-for-header */

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
/* %% [7.0] user's declarations go here */
#line 59 "scanner.l"


#line 1193 "scanner.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
/* %if-c-only */
			yyin = stdin;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! yyout )
/* %if-c-only */
			yyout = stdout;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 376 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 375 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 55 )
				fprintf( stderr, "--accepting rule at line %ld (\"%s\")\n",
				         (long)yy_rule_linenum[yy_act], yytext );
			else if ( yy_act == 55 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         yytext );
			else if ( yy_act == 56 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 61 "scanner.l"
return USE;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 62 "scanner.l"
return GIVE;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 63 "scanner.l"
return SORT;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 64 "scanner.l"
return MERGE;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 65 "scanner.l"
return FIELDS;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 66 "scanner.l"
return BUILD;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 67 "scanner.l"
return RECORD;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 68 "scanner.l"
return OUTREC;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 69 "scanner.l"
return INREC;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 70 "scanner.l"
return SUM;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 71 "scanner.l"
return INCLUDE;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 72 "scanner.l"
return OMIT;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 73 "scanner.l"
return COND;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 74 "scanner.l"
return ORG;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 75 "scanner.l"
return NONE;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 76 "scanner.l"
return COPY; 
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 77 "scanner.l"
return FORMAT;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 78 "scanner.l"
return OUTFIL;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 79 "scanner.l"
return FNAMES;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 80 "scanner.l"
return FILES;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 81 "scanner.l"
return STARTREC;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 82 "scanner.l"
return ENDREC;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 83 "scanner.l"
return SAVE;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 84 "scanner.l"
return OPTION;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 85 "scanner.l"
return SKIPREC;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 86 "scanner.l"
return STOPAFT;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 88 "scanner.l"
return TOKSKIP;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 89 "scanner.l"
printf("OCSort - Warning - Token skipped : "); ECHO; printf("\n"); // return TOKSKIP;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 90 "scanner.l"
printf("OCSort - Warning - Token skipped : "); ECHO; printf("\n"); // return TOKSKIP;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 91 "scanner.l"
printf("OCSort - Warning - Token skipped : "); ECHO; printf("\n"); // return TOKSKIP;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 92 "scanner.l"
printf("OCSort - Warning - Token skipped : "); ECHO; printf("\n"); // return TOKSKIP;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 93 "scanner.l"
printf("OCSort - Warning - Token skipped : "); ECHO; printf("\n"); // return TOKSKIP; 
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 94 "scanner.l"
printf("OCSort - Warning - Token skipped : "); ECHO; printf("\n"); // return TOKSKIP; 
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 95 "scanner.l"
printf("OCSort - Warning - Token skipped : "); ECHO; printf("\n"); // return TOKSKIP; 
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 96 "scanner.l"
printf("OCSort - Warning - Token skipped : "); ECHO; printf("\n"); // return TOKSKIP; 
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 99 "scanner.l"
return AND;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 100 "scanner.l"
return OR;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 103 "scanner.l"
yylval.string = _strdup(yytext) ;				return ORDER; 
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 104 "scanner.l"
yylval.number = strtol(yytext, &pEnd, 10) ;		return DIGIT;  
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 105 "scanner.l"
yylval.number = strtol(yytext, &pEnd, 10) ;		return DIGIT; 
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 106 "scanner.l"
yylval.llnumber = xstrtoll(yytext, &pEnd, 10) ;		return SIGNDIGITBIG;  
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 107 "scanner.l"
yylval.llnumber = xstrtoll(yytext, &pEnd, 10) ;		return SIGNDIGITBIG;  
	YY_BREAK
/* String C'      NFXA=''KK_NEW_'   */
/*  {  "'"*"''"*"'" */
case 43:
YY_RULE_SETUP
#line 112 "scanner.l"

	YY_BREAK

case 44:
YY_RULE_SETUP
#line 114 "scanner.l"

	YY_BREAK
case 45:
YY_RULE_SETUP
#line 115 "scanner.l"

	YY_BREAK
case 46:
YY_RULE_SETUP
#line 116 "scanner.l"

	YY_BREAK
case 47:
YY_RULE_SETUP
#line 117 "scanner.l"
STRING;
	YY_BREAK

/* String C''';'   */
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 120 "scanner.l"
{yylval.string=malloc(strlen(yytext)-1);
					 memcpy(yylval.string,yytext+1,strlen(yytext)-2);
					 yylval.string[strlen(yytext)-2]=0;
					 return STRING;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 126 "scanner.l"
yylval.string = _strdup(yytext) ; return XFIELDTYPE;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 127 "scanner.l"
yylval.string = _strdup(yytext) ; return CHARTYPE; 
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 128 "scanner.l"
yylval.string = _strdup(yytext) ; return LITERAL;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 129 "scanner.l"
yylval.string = _strdup(yytext) ; return STRING;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 130 "scanner.l"

	YY_BREAK
case 54:
YY_RULE_SETUP
#line 131 "scanner.l"
return yytext[0];
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 132 "scanner.l"
ECHO;
	YY_BREAK
#line 1587 "scanner.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */

/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
static int yy_get_next_buffer (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */

    static yy_state_type yy_get_previous_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 376 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 376 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 375);

		return yy_is_jam ? 0 : yy_current_state;
}

/* %if-c-only */

/* %endif */

/* %if-c-only */
#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

/* %endif */
/* %if-c++-only */
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and yylineno */

	return c;
}
/* %if-c-only */
#endif	/* ifndef YY_NO_INPUT */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
    void yyrestart  (FILE * input_file )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
static void yy_load_buffer_state  (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
/* %if-c-only */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )
/* %endif */
/* %if-c++-only */
/* %endif */

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
/* %endif */
/* %if-c++-only */
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
void yypop_buffer_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
static void yyensure_buffer_stack (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}
/* %endif */

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}
/* %endif */
/* %if-c++-only */
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/* %if-reentrant */
/* %endif */

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

/* %if-reentrant */
/* %endif */
    return 0;
}
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 132 "scanner.l"


