#line 2 "scanner.c"

#line 4 "scanner.c" 

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */

/* %if-c-only */
/* %if-not-reentrant */

/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
/* %endif */

/* %if-c-only */
    
/* %endif */

/* %if-c-only */

/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* %if-c++-only */
/* %endif */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* %not-for-header */

/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

/* %if-not-reentrant */
extern yy_size_t yyleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
extern FILE *yyin, *yyout;
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
	FILE *yy_input_file;
/* %endif */

/* %if-c++-only */
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

/* %if-not-reentrant */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */

/* %if-not-reentrant */
/* %not-for-header */

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;
/* %ok-for-header */

/* %endif */

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

/* %endif */

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */

#define yywrap() 1
#define YY_SKIP_YYWRAP

#define FLEX_DEBUG

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

/* %if-c-only Standard (non-C++) definition */

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;

/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 54
#define YY_END_OF_BUFFER 55
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[372] =
    {   0,
       51,   51,   55,   53,   52,   54,   50,   53,   53,   53,
       51,   39,   38,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   52,   50,
       50,    0,    0,   48,    0,   40,    0,    0,    0,    0,
        0,    0,    0,   51,   39,   49,   51,   49,   51,   51,
       51,   49,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   49,   51,   51,   51,   51,   51,   51,   51,
       51,   49,   48,    0,    0,   40,    0,    0,    0,    0,
        0,    0,   39,   51,   51,   51,   27,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,

       51,   14,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   10,    1,   51,    0,   43,    0,   40,    0,    0,
        0,    0,    0,   37,    0,   39,   51,   13,   51,   16,
       51,   51,   51,   51,   51,   51,    2,   51,   51,   51,
       51,   51,   15,   12,   51,   51,   51,   51,   51,   51,
       23,   51,    3,   51,   51,   51,    0,   40,    0,   36,
        0,    0,    0,    0,   39,    6,   51,   51,   51,   51,
       20,   51,   51,   51,    9,   51,    4,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   40,    0,
        0,    0,    0,   41,   51,   22,   32,    5,   19,   17,

       51,   51,   51,   24,   18,    8,    7,   51,   47,   51,
       51,   51,   51,   42,    0,   33,    0,    0,   41,   30,
       11,   51,   51,   51,   25,   51,   26,    0,   51,   42,
       31,    0,    0,   41,   51,   34,   28,   21,    0,   51,
       42,   35,   29,   41,   51,    0,   51,   42,   41,   51,
        0,   51,   42,   41,   51,    0,   51,   42,   41,   51,
        0,   51,   42,   41,    0,   51,    0,   51,   42,   41,
        0,   51,    0,    0,   51,   42,   41,    0,   51,    0,
        0,   42,   41,    0,   51,    0,    0,   42,   41,    0,
       51,   46,    0,   42,   41,    0,   51,    0,   42,   41,

        0,   51,    0,   42,   41,    0,    0,   42,   41,    0,
        0,   42,   41,    0,    0,   42,   41,    0,    0,   42,
       41,    0,    0,   42,   41,    0,    0,   42,   41,    0,
        0,   42,   41,    0,    0,   42,   41,    0,    0,   42,
       41,    0,    0,   42,   41,    0,    0,   42,   41,    0,
        0,   42,   41,    0,    0,   42,    0,    0,    0,    0,
        0,   44,    0,    0,    0,    0,    0,    0,    0,   45,
        0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    4,    4,    4,    4,    6,    7,
        7,    8,    9,   10,   11,   12,    8,   13,   14,   15,
       16,   16,   16,   16,   16,   16,   16,    4,   17,    1,
       18,    1,    1,    1,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   28,   41,   42,   43,
        4,    1,    4,    1,   28,    1,   44,   45,   46,   47,

       48,   49,   50,   51,   52,   28,   53,   54,   55,   56,
       57,   58,   59,   60,   61,   62,   63,   64,   28,   65,
       66,   67,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[68] =
    {   0,
        1,    1,    2,    3,    1,    3,    4,    5,    5,    4,
        5,    6,    6,    6,    6,    7,    3,    5,    7,    7,
        7,    7,    6,    7,    7,    7,    7,    7,    7,    6,
        7,    6,    7,    7,    7,    6,    6,    6,    7,    7,
        6,    6,    7,    7,    7,    7,    7,    6,    7,    7,
        7,    7,    7,    6,    7,    6,    7,    7,    7,    6,
        6,    6,    7,    7,    6,    6,    7
    } ;

static yyconst flex_int16_t yy_base[382] =
    {   0,
        0,    0,  350, 1065,   66, 1065,    0,   71,   70,   88,
        0,   78,    0,   60,   71,   70,   81,   43,   69,   83,
       70,  115,   88,   92,  123,   80,   77,  108,  145, 1065,
        0,  329,  186,  295,  204,  144,  197,  107,  120,  139,
      167,  165,  179,    0,  168,    0,  190,    0,  194,  196,
      181,  208,  204,  193,  193,  213,  209,  214,  208,  201,
      222,  213,    0,  245,  215,  238,  222,  248,  240,  245,
      244,    0, 1065,  307,  162,  271,  255,  248,  257,  256,
      287,  268,  313,  276,  297,  279,  286,  312,  303,  311,
      305,  307,  316,  311,  319,  322,  322,  325,  326,  313,

      325,    0,  330,  325,  330,  330,  330,  336,  333,  340,
      346,    0,    0,  341,  379, 1065,  402,  400,  330,  357,
      373,  375,  389, 1065,  368,  413,  385,    0,  387,    0,
      388,  388,  398,  385,  401,  411,    0,  394,  410,  400,
      414,  401,    0,    0,  407,  414,  420,  411,  408,  414,
        0,  415,    0,  414,  425,  434,  473,  471,  457, 1065,
      447,  435,  435,  441,  478,    0,  446,  467,  459,  461,
        0,  462,  462,  479,    0,  461,    0,  485,  475,  478,
      488,  488,  488,  482,  489,  479,  492,  488,  530,  489,
      491,  511,  510,  546,  502,    0,    0,    0,    0,    0,

      524,  508,  521,    0,    0,    0,    0,  530,    0,  532,
      531,  518,  580,  552,  531, 1065,  543,  550,  586,    0,
        0,  541,  562,  573,    0,  582,    0,  568,  569,  595,
     1065,  582,  592,  607,  585,    0,    0,    0,  579,  580,
      611, 1065, 1065,  618,  595,  601,  604,  630,  634,  632,
      625,  626,  641,  652,  628,  628,  630,  656,  674,  690,
      654,  655,  696,  700,  656,  665,  276,  720,  705,  709,
      698,  701,  270,  709,  219,  731,  756,  705,  706,  219,
      662,  774,  778,  721,  726,  202,  721,  782,  786,  723,
      727, 1065,  754,  790,  796,  782,  788,  782,  803,  807,

      161,  155,  803,  812,  820,  787,  793,  827,  831,  789,
      799,  843,  849,  810,  814,  853,  862,  837,  840,  866,
      873,  830,  850,  877,  886,  845,  852,  890,  896,  882,
      855,  900,  909,  154,  875,  913,  917,  881,  881,  921,
      932,  900,  916,  936,  940,  921,  917,  952,  956,  929,
      922,  960,    0,  938,  107, 1065,  931,  102,  935,   83,
      936, 1065,  941,  957,  944,  950,   87,   81,   52, 1065,
     1065, 1007, 1014, 1016, 1023, 1030, 1035, 1040, 1047, 1054,
     1058
    } ;

static yyconst flex_int16_t yy_def[382] =
    {   0,
      371,    1,  371,  371,  371,  371,  372,  373,  371,  371,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  371,  371,
      372,  375,  376,  371,  373,  371,  371,  371,  371,  371,
      371,  371,  371,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  371,  376,  377,  371,  371,  371,  371,  371,
      371,  371,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,

      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  378,  371,  377,  371,  371,  371,
      371,  371,  371,  371,  371,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  378,  371,  371,  371,
      371,  371,  371,  371,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  371,  371,
      371,  371,  371,  374,  374,  374,  374,  374,  374,  374,

      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  379,  371,  371,  371,  371,  371,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  371,  374,  371,
      371,  371,  371,  374,  374,  374,  374,  374,  371,  374,
      371,  371,  371,  374,  374,  371,  374,  371,  374,  374,
      371,  374,  371,  374,  374,  371,  374,  371,  374,  380,
      371,  374,  371,  374,  371,  374,  381,  374,  371,  374,
      371,  374,  371,  371,  374,  371,  374,  371,  374,  371,
      371,  371,  374,  371,  374,  371,  371,  371,  374,  371,
      374,  371,  371,  371,  374,  371,  374,  371,  371,  374,

      371,  374,  371,  371,  374,  371,  371,  371,  374,  371,
      371,  371,  374,  371,  371,  371,  374,  371,  371,  371,
      374,  371,  371,  371,  374,  371,  371,  371,  374,  371,
      371,  371,  374,  371,  371,  371,  374,  371,  371,  371,
      374,  371,  371,  371,  374,  371,  371,  371,  374,  371,
      371,  371,  374,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
        0,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371
    } ;

static yyconst flex_int16_t yy_nxt[1133] =
    {   0,
        4,    5,    6,    4,    7,    8,    4,    4,    9,   10,
        9,   11,   12,   12,   12,   12,    4,    4,   13,   14,
       15,   13,   16,   17,   18,   11,   19,   11,   11,   11,
       20,   21,   22,   23,   11,   24,   25,   11,   26,   11,
       11,   27,   28,   13,   14,   15,   13,   16,   17,   18,
       11,   19,   11,   11,   20,   21,   22,   23,   11,   24,
       25,   11,   26,   11,   11,   27,   28,   29,  370,   55,
       30,   32,   32,   32,   33,   32,   34,   33,   32,   32,
       33,   32,   36,   36,   36,   36,   46,   33,   32,   37,
       45,   45,   45,   45,   55,  369,   48,  368,   47,  362,

       56,   50,   58,   49,   51,   57,   38,   52,   39,   63,
       40,   46,   53,   54,   64,  360,   70,  358,   71,   41,
       42,   48,   47,   43,   56,   50,   58,   49,   51,   72,
       57,   38,   52,   39,   63,   40,   53,   54,   77,   64,
       70,   65,   71,   41,   42,   59,   29,   43,   60,   30,
       61,   66,   78,   62,   72,   67,   76,   76,   76,   76,
       68,   69,   77,  338,  306,  115,   65,  116,  115,   59,
      306,  115,   60,   79,   61,   66,   78,   62,  115,   67,
       83,   83,   83,   83,   68,   69,   32,   32,   32,   33,
       32,   34,   33,   32,   32,   33,   32,   79,   37,   80,

       81,   82,   33,   32,   32,   32,   32,   33,   32,   34,
       33,   32,   32,   33,   32,   38,   84,   87,  292,   88,
       33,   32,   91,   80,   81,   85,   82,   86,   92,   42,
       89,  286,   93,   94,  100,   98,  280,   90,  101,   96,
       38,   84,   87,   88,   97,   99,  102,   91,   95,   85,
      103,   86,   92,   42,  107,   89,   93,  109,   94,  100,
       98,   90,  101,   96,  108,  104,  110,  113,   97,   99,
      112,  102,   95,  114,  103,  105,  119,  122,  107,  120,
      111,  109,  106,  118,  118,  118,  118,  280,  123,  108,
      104,  110,  113,  274,  112,  121,  124,  114,  125,  105,

       75,  119,  122,  120,  111,  127,  106,   32,   32,   32,
       32,   32,   34,   32,   32,   32,   32,   32,  128,  121,
      130,  131,  125,   32,   32,  126,  126,  126,  126,  127,
      132,  159,  133,  134,   73,  135,  129,  136,  137,  160,
      138,  139,  140,  128,  130,  131,  141,  142,  143,  371,
      144,  145,  151,  146,  371,  132,  133,  148,  134,  135,
      129,  136,  149,  137,  138,  147,  139,  140,  150,  152,
      153,  141,  142,  143,  144,  154,  145,  151,  146,  155,
      156,  148,  115,  371,  116,  115,  149,  371,  115,  147,
      123,  162,  150,  152,  153,  115,  161,  163,  124,  154,

      164,  371,  371,  155,  156,  115,  166,  116,  115,  167,
      168,  115,  158,  158,  158,  158,  162,  169,  115,  170,
      161,  171,  163,  172,  164,  165,  165,  165,  165,  173,
      175,  166,  174,  176,  167,  168,  177,  371,  178,  179,
      180,  169,  181,  187,  170,  171,  182,  183,  172,  184,
      185,  186,  188,  371,  173,  175,  174,  176,  159,  371,
      371,  177,  178,  179,  191,  180,  160,  181,  187,  190,
      182,  183,  192,  184,  185,  186,  371,  188,  116,  371,
      193,  195,  371,  189,  189,  189,  189,  196,  191,  371,
      194,  194,  194,  194,  190,  197,  192,  198,  199,  200,

      201,  371,  202,  203,  193,  195,  204,  205,  206,  207,
      208,  210,  196,  209,  211,  212,  371,  213,  371,  197,
      371,  198,  199,  200,  215,  201,  202,  216,  203,  217,
      204,  205,  218,  206,  207,  208,  210,  209,  211,  220,
      212,  213,  214,  214,  214,  214,  221,  223,  215,  222,
      224,  216,  225,  226,  217,  227,  371,  218,  219,  219,
      219,  219,  371,  220,  230,  230,  230,  230,  231,  232,
      233,  221,  223,  222,  371,  224,  371,  225,  226,  227,
      228,  228,  235,  228,  228,  228,  228,  228,  228,  228,
      228,  236,  231,  237,  232,  233,  228,  228,  234,  234,

      234,  234,  238,  371,  239,  240,  235,  241,  241,  241,
      241,  242,  243,  371,  245,  236,  246,  247,  237,  244,
      244,  244,  244,  248,  248,  248,  248,  238,  239,  240,
      249,  249,  249,  249,  250,  242,  251,  243,  245,  252,
      246,  247,  253,  253,  253,  253,  254,  254,  254,  254,
      255,  256,  257,  258,  258,  258,  258,  260,  250,  261,
      251,  262,  371,  252,  259,  259,  259,  259,  263,  263,
      263,  263,  371,  371,  371,  255,  256,  257,  267,  268,
      287,  260,  371,  261,  371,  262,  264,  264,  264,  264,
      265,  265,  271,  265,  265,  265,  265,  265,  265,  265,

      265,  272,  371,  267,  268,  287,  265,  265,  269,  269,
      269,  269,  270,  270,  270,  270,  271,  276,  276,  276,
      276,  277,  277,  277,  277,  272,  273,  273,  273,  273,
      273,  275,  275,  275,  275,  278,  371,  274,  279,  281,
      284,  285,  275,  282,  282,  282,  282,  290,  371,  275,
      293,  275,  291,  371,  296,  275,  275,  275,  297,  278,
      275,  275,  279,  281,  284,  285,  371,  275,  283,  283,
      283,  283,  290,  275,  293,  275,  371,  291,  296,  275,
      275,  275,  297,  298,  275,  275,  288,  288,  288,  288,
      289,  289,  289,  289,  294,  294,  294,  294,  295,  295,

      295,  295,  299,  299,  299,  299,  301,  298,  300,  300,
      300,  300,  302,  371,  303,  304,  304,  304,  304,  305,
      305,  305,  305,  307,  308,  308,  308,  308,  310,  311,
      314,  301,  309,  309,  309,  309,  315,  302,  303,  312,
      312,  312,  312,  313,  313,  313,  313,  318,  307,  319,
      371,  371,  310,  311,  314,  316,  316,  316,  316,  322,
      315,  317,  317,  317,  317,  320,  320,  320,  320,  323,
      326,  318,  327,  319,  321,  321,  321,  321,  324,  324,
      324,  324,  330,  331,  322,  325,  325,  325,  325,  328,
      328,  328,  328,  323,  326,  334,  335,  327,  329,  329,

      329,  329,  332,  332,  332,  332,  330,  331,  333,  333,
      333,  333,  336,  336,  336,  336,  339,  342,  343,  330,
      335,  337,  337,  337,  337,  340,  340,  340,  340,  341,
      341,  341,  341,  344,  344,  344,  344,  346,  347,  371,
      339,  342,  343,  330,  345,  345,  345,  345,  348,  348,
      348,  348,  349,  349,  349,  349,  350,  351,  354,  355,
      357,  346,  359,  347,  352,  352,  352,  352,  353,  353,
      353,  353,  356,  356,  356,  356,  361,  363,  364,  365,
      350,  351,  354,  355,  366,  357,  359,  367,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,

      361,  363,  364,  371,  365,  371,  371,  371,  366,  371,
      371,  367,   31,   31,   35,   35,   35,   35,   35,   35,
       35,   44,   44,   32,   32,   32,   32,   32,   32,   32,
       74,   74,   74,   74,   74,   74,   74,  117,  117,  371,
      117,  117,  157,  157,  371,  157,  157,  229,  371,  229,
      229,  229,  229,  229,  266,  371,  266,  266,  266,  266,
      266,  273,  273,  273,    3,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,

      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371
    } ;

static yyconst flex_int16_t yy_chk[1133] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    5,  369,   18,
        5,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    9,    9,    9,    9,   14,    8,    8,   10,
       12,   12,   12,   12,   18,  368,   15,  367,   14,  360,

       19,   16,   21,   15,   16,   20,   10,   17,   10,   23,
       10,   14,   17,   17,   24,  358,   26,  355,   27,   10,
       10,   15,   14,   10,   19,   16,   21,   15,   16,   28,
       20,   10,   17,   10,   23,   10,   17,   17,   38,   24,
       26,   25,   27,   10,   10,   22,   29,   10,   22,   29,
       22,   25,   39,   22,   28,   25,   36,   36,   36,   36,
       25,   25,   38,  334,  302,   75,   25,   75,   75,   22,
      301,   75,   22,   40,   22,   25,   39,   22,   75,   25,
       45,   45,   45,   45,   25,   25,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   40,   37,   41,

       42,   43,   33,   33,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   37,   47,   50,  286,   51,
       35,   35,   53,   41,   42,   49,   43,   49,   54,   37,
       52,  280,   55,   56,   59,   58,  275,   52,   60,   57,
       37,   47,   50,   51,   57,   58,   61,   53,   56,   49,
       62,   49,   54,   37,   65,   52,   55,   67,   56,   59,
       58,   52,   60,   57,   66,   64,   68,   70,   57,   58,
       69,   61,   56,   71,   62,   64,   77,   80,   65,   78,
       68,   67,   64,   76,   76,   76,   76,  273,   81,   66,
       64,   68,   70,  267,   69,   79,   81,   71,   82,   64,

       34,   77,   80,   78,   68,   84,   64,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   85,   79,
       86,   87,   82,   74,   74,   83,   83,   83,   83,   84,
       88,  119,   89,   90,   32,   91,   85,   92,   93,  119,
       94,   95,   96,   85,   86,   87,   97,   98,   99,    3,
      100,  101,  107,  103,    0,   88,   89,  104,   90,   91,
       85,   92,  105,   93,   94,  103,   95,   96,  106,  108,
      109,   97,   98,   99,  100,  110,  101,  107,  103,  111,
      114,  104,  115,    0,  115,  115,  105,    0,  115,  103,
      123,  121,  106,  108,  109,  115,  120,  122,  123,  110,

      125,    0,    0,  111,  114,  117,  127,  117,  117,  129,
      131,  117,  118,  118,  118,  118,  121,  132,  117,  133,
      120,  134,  122,  135,  125,  126,  126,  126,  126,  136,
      139,  127,  138,  140,  129,  131,  141,    0,  142,  145,
      146,  132,  147,  155,  133,  134,  148,  149,  135,  150,
      152,  154,  156,    0,  136,  139,  138,  140,  159,    0,
        0,  141,  142,  145,  162,  146,  159,  147,  155,  161,
      148,  149,  163,  150,  152,  154,  157,  156,  157,  157,
      164,  167,  157,  158,  158,  158,  158,  168,  162,  157,
      165,  165,  165,  165,  161,  169,  163,  170,  172,  173,

      174,    0,  176,  178,  164,  167,  179,  180,  181,  182,
      183,  185,  168,  184,  186,  187,    0,  188,    0,  169,
        0,  170,  172,  173,  190,  174,  176,  191,  178,  192,
      179,  180,  193,  181,  182,  183,  185,  184,  186,  195,
      187,  188,  189,  189,  189,  189,  201,  203,  190,  202,
      208,  191,  210,  211,  192,  212,    0,  193,  194,  194,
      194,  194,    0,  195,  214,  214,  214,  214,  215,  217,
      218,  201,  203,  202,    0,  208,    0,  210,  211,  212,
      213,  213,  222,  213,  213,  213,  213,  213,  213,  213,
      213,  223,  215,  224,  217,  218,  213,  213,  219,  219,

      219,  219,  226,    0,  228,  229,  222,  230,  230,  230,
      230,  232,  233,    0,  235,  223,  239,  240,  224,  234,
      234,  234,  234,  241,  241,  241,  241,  226,  228,  229,
      244,  244,  244,  244,  245,  232,  246,  233,  235,  247,
      239,  240,  248,  248,  248,  248,  249,  249,  249,  249,
      250,  251,  252,  253,  253,  253,  253,  255,  245,  256,
      246,  257,    0,  247,  254,  254,  254,  254,  258,  258,
      258,  258,    0,    0,    0,  250,  251,  252,  261,  262,
      281,  255,    0,  256,    0,  257,  259,  259,  259,  259,
      260,  260,  265,  260,  260,  260,  260,  260,  260,  260,

      260,  266,    0,  261,  262,  281,  260,  260,  263,  263,
      263,  263,  264,  264,  264,  264,  265,  269,  269,  269,
      269,  270,  270,  270,  270,  266,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  271,    0,  268,  272,  274,
      278,  279,  268,  276,  276,  276,  276,  284,    0,  268,
      287,  268,  285,    0,  290,  268,  268,  268,  291,  271,
      268,  268,  272,  274,  278,  279,    0,  268,  277,  277,
      277,  277,  284,  268,  287,  268,    0,  285,  290,  268,
      268,  268,  291,  293,  268,  268,  282,  282,  282,  282,
      283,  283,  283,  283,  288,  288,  288,  288,  289,  289,

      289,  289,  294,  294,  294,  294,  296,  293,  295,  295,
      295,  295,  297,    0,  298,  299,  299,  299,  299,  300,
      300,  300,  300,  303,  304,  304,  304,  304,  306,  307,
      310,  296,  305,  305,  305,  305,  311,  297,  298,  308,
      308,  308,  308,  309,  309,  309,  309,  314,  303,  315,
        0,    0,  306,  307,  310,  312,  312,  312,  312,  318,
      311,  313,  313,  313,  313,  316,  316,  316,  316,  319,
      322,  314,  323,  315,  317,  317,  317,  317,  320,  320,
      320,  320,  326,  327,  318,  321,  321,  321,  321,  324,
      324,  324,  324,  319,  322,  330,  331,  323,  325,  325,

      325,  325,  328,  328,  328,  328,  326,  327,  329,  329,
      329,  329,  332,  332,  332,  332,  335,  338,  339,  330,
      331,  333,  333,  333,  333,  336,  336,  336,  336,  337,
      337,  337,  337,  340,  340,  340,  340,  342,  343,    0,
      335,  338,  339,  330,  341,  341,  341,  341,  344,  344,
      344,  344,  345,  345,  345,  345,  346,  347,  350,  351,
      354,  342,  357,  343,  348,  348,  348,  348,  349,  349,
      349,  349,  352,  352,  352,  352,  359,  361,  363,  364,
      346,  347,  350,  351,  365,  354,  357,  366,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

      359,  361,  363,    0,  364,    0,    0,    0,  365,    0,
        0,  366,  372,  372,  373,  373,  373,  373,  373,  373,
      373,  374,  374,  375,  375,  375,  375,  375,  375,  375,
      376,  376,  376,  376,  376,  376,  376,  377,  377,    0,
      377,  377,  378,  378,    0,  378,  378,  379,    0,  379,
      379,  379,  379,  379,  380,    0,  380,  380,  380,  380,
      380,  381,  381,  381,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,

      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 1;

static yyconst flex_int16_t yy_rule_linenum[54] =
    {   0,
       44,   45,   46,   47,   48,   49,   50,   51,   52,   53,
       54,   55,   56,   57,   58,   59,   60,   61,   62,   63,
       64,   65,   66,   67,   68,   69,   71,   72,   73,   74,
       75,   76,   77,   78,   79,   82,   83,   87,   88,   93,
       95,   97,  111,  113,  114,  115,  116,  137,  143,  145,
      147,  149,  150
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#line 2 "scanner.l"
#include <io.h> 
#include "parser.h"
void yyerror(const char *error) {
	printf("Error : %s\n",error);
	if(yytext != NULL)
		printf("Error near element : %s\n", yytext);
} 
#define YY_NO_INPUT
/*	DIGIT		[0-9]{1,5}
DIGITBIG	[0-9]{6,32} */
/* original scanner for string		STRING		[a-zA-Z0-9\./]* */
/* version modified for : separator	STRING		[a-zA-Z0-9\.\/\\\:\_\;]*  */
/*  TOKEND      END  */
/* ok \"[^\"]*\" */
/*   "'"[^']*[']{2,}"'"	{yylval.string=malloc(strlen(yytext)-1);  */
#line 939 "scanner.c"

#define INITIAL 0

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */

static int yy_init_globals (void );

/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* %if-bison-bridge */
/* %endif */

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

/* %not-for-header */

/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */

/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\
/* %if-c++-only C++ definition \ */\
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */

/* %ok-for-header */

/* %not-for-header */

/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */

extern int yylex (void);

#define YY_DECL int yylex (void)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %not-for-header */

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
/* %% [7.0] user's declarations go here */
#line 42 "scanner.l"


#line 1170 "scanner.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
/* %if-c-only */
			yyin = stdin;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! yyout )
/* %if-c-only */
			yyout = stdout;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 372 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 371 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 54 )
				fprintf( stderr, "--accepting rule at line %ld (\"%s\")\n",
				         (long)yy_rule_linenum[yy_act], yytext );
			else if ( yy_act == 54 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         yytext );
			else if ( yy_act == 55 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 44 "scanner.l"
return USE;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 45 "scanner.l"
return GIVE;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 46 "scanner.l"
return SORT;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 47 "scanner.l"
return MERGE;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 48 "scanner.l"
return FIELDS;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 49 "scanner.l"
return BUILD;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 50 "scanner.l"
return RECORD;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 51 "scanner.l"
return OUTREC;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 52 "scanner.l"
return INREC;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 53 "scanner.l"
return SUM;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 54 "scanner.l"
return INCLUDE;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 55 "scanner.l"
return OMIT;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 56 "scanner.l"
return COND;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 57 "scanner.l"
return ORG;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 58 "scanner.l"
return NONE;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 59 "scanner.l"
return COPY; 
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 60 "scanner.l"
return FORMAT;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 61 "scanner.l"
return OUTFIL;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 62 "scanner.l"
return FNAMES;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 63 "scanner.l"
return FILES;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 64 "scanner.l"
return STARTREC;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 65 "scanner.l"
return ENDREC;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 66 "scanner.l"
return SAVE;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 67 "scanner.l"
return OPTION;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 68 "scanner.l"
return SKIPREC;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 69 "scanner.l"
return STOPAFT;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 71 "scanner.l"
return TOKSKIP;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 72 "scanner.l"
printf("ENGSORT - Warning - Token skipped : "); ECHO; printf("\n"); // return TOKSKIP;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 73 "scanner.l"
printf("ENGSORT - Warning - Token skipped : "); ECHO; printf("\n"); // return TOKSKIP;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 74 "scanner.l"
printf("ENGSORT - Warning - Token skipped : "); ECHO; printf("\n"); // return TOKSKIP;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 75 "scanner.l"
printf("ENGSORT - Warning - Token skipped : "); ECHO; printf("\n"); // return TOKSKIP;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 76 "scanner.l"
printf("ENGSORT - Warning - Token skipped : "); ECHO; printf("\n"); // return TOKSKIP; 
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 77 "scanner.l"
printf("ENGSORT - Warning - Token skipped : "); ECHO; printf("\n"); // return TOKSKIP; 
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 78 "scanner.l"
printf("ENGSORT - Warning - Token skipped : "); ECHO; printf("\n"); // return TOKSKIP; 
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 79 "scanner.l"
printf("ENGSORT - Warning - Token skipped : "); ECHO; printf("\n"); // return TOKSKIP; 
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 82 "scanner.l"
return AND;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 83 "scanner.l"
return OR;
	YY_BREAK
/* yylval.string[0] = yytext[0]; return ORDER; */
case 38:
YY_RULE_SETUP
#line 87 "scanner.l"
yylval.string = _strdup(yytext) ; return ORDER; 
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 88 "scanner.l"
yylval.number = atoi(yytext) ; return NUMBER;  
	YY_BREAK
/* in questo caso ritorna una stringa che poi deve essere trasformata in numero */
case 40:
YY_RULE_SETUP
#line 93 "scanner.l"
yylval.number = atoi(yytext) ; return NUMBER;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 95 "scanner.l"
yylval.string = _strdup(yytext) ; return SIGNDIGITBIG;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 97 "scanner.l"
yylval.string = _strdup(yytext) ; return SIGNDIGITBIG; 
	YY_BREAK
/* return a string for conversion 
			{yylval.number = atol(yytext+1) ; 
				if(yytext[0] == '-')
					yylval.number = yylval.number * -1;
				return NUMBER;
				}
		*/
/* String C'      NFNAME=''ZZ_FIX_'   */
/*  {  "'"*"''"*"'" */
case 43:
YY_RULE_SETUP
#line 111 "scanner.l"

	YY_BREAK

case 44:
YY_RULE_SETUP
#line 113 "scanner.l"

	YY_BREAK
case 45:
YY_RULE_SETUP
#line 114 "scanner.l"

	YY_BREAK
case 46:
YY_RULE_SETUP
#line 115 "scanner.l"

	YY_BREAK
case 47:
YY_RULE_SETUP
#line 116 "scanner.l"
STRING;
	YY_BREAK

/* String C''';'   */
/*
	"'''"{STRING}*{SPECHR}*"'"	{yylval.string=malloc(strlen(yytext)-1);
				 memcpy(yylval.string,yytext+1,strlen(yytext)-2);
				 yylval.string[strlen(yytext)-2]=0;
				 return STRING;}

	*/
/* String C'  WHERE GD_DATARIL ='''   */
/* old "'"[^']*[']{2,}"'"	{yylval.string=malloc(strlen(yytext)-1); */
/*
	"'"[^']*[']{2,}{STRING}*{SPECHR}*"'"	{yylval.string=malloc(strlen(yytext)-1);
				 memcpy(yylval.string,yytext+1,strlen(yytext)-2);
				 yylval.string[strlen(yytext)-2]=0;
				 return STRING;}

	*/
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 137 "scanner.l"
{yylval.string=malloc(strlen(yytext)-1);
					 memcpy(yylval.string,yytext+1,strlen(yytext)-2);
					 yylval.string[strlen(yytext)-2]=0;
					 return STRING;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 143 "scanner.l"
yylval.string = _strdup(yytext) ; return FIELDTYPE;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 145 "scanner.l"
yylval.string = _strdup(yytext) ; return LITERAL;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 147 "scanner.l"
yylval.string = _strdup(yytext) ; return STRING;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 149 "scanner.l"

	YY_BREAK
case 53:
YY_RULE_SETUP
#line 150 "scanner.l"
return yytext[0];
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 151 "scanner.l"
ECHO;
	YY_BREAK
#line 1584 "scanner.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */

/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
static int yy_get_next_buffer (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */

    static yy_state_type yy_get_previous_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 372 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 372 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 371);

		return yy_is_jam ? 0 : yy_current_state;
}

/* %if-c-only */

/* %endif */

/* %if-c-only */
#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

/* %endif */
/* %if-c++-only */
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and yylineno */

	return c;
}
/* %if-c-only */
#endif	/* ifndef YY_NO_INPUT */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
    void yyrestart  (FILE * input_file )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
static void yy_load_buffer_state  (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
/* %if-c-only */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )
/* %endif */
/* %if-c++-only */
/* %endif */

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
/* %endif */
/* %if-c++-only */
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
void yypop_buffer_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
static void yyensure_buffer_stack (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}
/* %endif */

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}
/* %endif */
/* %if-c++-only */
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/* %if-reentrant */
/* %endif */

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

/* %if-reentrant */
/* %endif */
    return 0;
}
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 151 "scanner.l"



