#line 2 "scanner.c"

#line 4 "scanner.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */

/* %if-c-only */
/* %if-not-reentrant */

/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
/* %endif */

/* %if-c-only */
    
/* %endif */

/* %if-c-only */

/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* %if-c++-only */
/* %endif */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* %not-for-header */

/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

/* %if-not-reentrant */
extern yy_size_t yyleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
extern FILE *yyin, *yyout;
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
	FILE *yy_input_file;
/* %endif */

/* %if-c++-only */
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

/* %if-not-reentrant */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */

/* %if-not-reentrant */
/* %not-for-header */

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;
/* %ok-for-header */

/* %endif */

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

/* %endif */

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */

#define yywrap() 1
#define YY_SKIP_YYWRAP

#define FLEX_DEBUG

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

/* %if-c-only Standard (non-C++) definition */

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;

/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 66
#define YY_END_OF_BUFFER 67
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[437] =
    {   0,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   67,   65,   64,   66,   65,   65,   65,   65,
       63,   50,   63,   63,   63,   54,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   55,   63,   62,
       62,   62,   49,   49,   59,   59,   59,   58,   58,   63,
       63,   63,   63,   64,    0,    0,    0,    0,    0,    0,
        0,    0,   61,    0,    0,    0,   51,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   63,   50,   57,
       57,   60,   63,   60,   63,   63,   63,   63,   48,   60,
       60,   63,   63,   48,   63,   48,   63,   63,   48,   48,

       63,   48,   63,   63,   63,   63,   63,   60,   63,   63,
       63,   63,   63,   48,   63,   63,   63,   63,   60,   62,
       56,   56,   56,   56,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   51,
        0,   45,    0,    0,    0,    0,    0,    0,    0,    0,
       47,   50,   63,   60,   63,   63,   60,   60,    5,   63,
       63,   63,   63,   63,   63,   63,   63,   15,   63,   63,
       63,   63,   63,   20,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   32,   33,   63,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,   51,    0,    0,    0,    0,    0,   46,    0,   50,
       63,    2,   63,    4,   63,   63,   63,   63,   63,   63,
       12,   63,   63,   63,   63,   17,   18,   63,   63,   63,
       63,   63,   25,   63,   27,   63,   63,   63,   63,   63,
        0,    0,    0,    0,    0,   17,   18,    0,   25,    0,
        0,    0,    0,    0,    0,    0,   51,    0,   44,    0,
        0,    0,    0,   50,    1,   63,   63,   63,   63,    9,
       63,   63,   63,   14,   16,   63,   17,   17,   63,   63,
       63,   63,   63,   25,   25,   63,   30,   63,   63,   63,
       63,    0,    9,    0,    0,    0,    0,    0,   30,    0,

        0,    0,    0,    0,    3,   51,    0,    0,    0,    0,
       52,    1,    1,   63,    6,   40,    8,    9,    9,   10,
       11,   63,   63,   19,   21,   23,   24,   63,   63,   63,
       63,   63,   34,   35,    6,   10,   11,    0,   23,    0,
        0,    0,    0,   34,   35,   53,    0,   41,    0,    0,
       52,   38,    0,    7,   10,   10,   11,   11,   13,   63,
       22,   63,   26,   63,   63,   29,   13,   26,    0,    0,
       29,   53,   39,    0,    0,   52,    7,   42,   36,    0,
       31,   28,   28,   53,   43,   37,   52,   31,   53,   52,
       53,   52,   53,   52,   53,   52,   53,   52,   53,   52,

       53,   52,   53,   52,   53,   52,   53,   52,   53,   52,
       53,   52,   53,   52,   53,   52,   53,   52,   53,   52,
       53,   52,   53,   52,   53,   52,   53,   52,   53,   52,
       53,   52,   53,   52,   53,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    4,    5,    6,
        7,    1,    8,    9,   10,   11,    1,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,    1,    1,    1,
       13,    1,    1,    1,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   11,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   11,   35,   36,   37,
        1,    1,    1,    1,   11,    1,   38,   39,   40,   41,

       42,   43,   44,   45,   46,   11,   47,   48,   49,   50,
       51,   52,   53,   54,   55,   56,   57,   58,   11,   59,
       60,   61,    1,   62,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[63] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        2,    2,    1,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    1
    } ;

static yyconst flex_int16_t yy_base[439] =
    {   0,
        0,    0,   49,   50,   53,   54,   63,   69,   70,   77,
       89,  101,  943,  944,  155,  944,  937,  144,  929,  212,
        0,  126,   50,  148,  142,  249,  205,   47,   57,  109,
       66,  149,  252,   98,   98,  296,   90,  110,  137,  142,
      257,  163,    0,    0,  290,    0,  191,  309,    0,  185,
      300,  241,  180,    0,  186,  336,  191,  197,  334,  347,
      201,  935,  944,  364,  266,  202,  927,  413,   67,  289,
      214,  218,  296,  252,  343,  278,   72,    0,  408,    0,
      944,    0,  291,    0,  299,  343,  357,  355,  341,  360,
        0,  363,  358,    0,  372,    0,  406,  373,    0,    0,

      380,    0,  411,  396,  393,  406,  397,    0,  438,  404,
      419,  427,  434,    0,  452,  447,  455,  443,    0,    0,
        0,    0,    0,    0,  459,  453,  466,  453,  468,  459,
      464,  456,  455,  469,  468,  479,  463,  493,  471,  926,
      124,  944,  928,  485,  479,  478,  497,  213,  495,  284,
      944,  512,  497,    0,  505,  491,    0,    0,  501,  518,
      509,  516,  511,  512,  522,  517,  524,    0,  528,  535,
      536,  527,  540,    0,  549,  540,  542,  552,  547,  544,
      558,  551,  554,    0,    0,  568,  555,  569,  563,  565,
      571,  578,  565,  568,  583,  574,  585,  580,  587,  602,

      580,  924,  285,  583,  610,  609,  414,  944,  601,  620,
      612,    0,  612,    0,  617,  613,  621,  612,  626,  631,
        0,  613,  633,  632,  624,  146,    0,  636,  642,  647,
      636,  637,  674,  642,    0,  643,  645,  664,  659,  655,
      668,  660,  674,  679,  661,  200,  944,  679,  696,  670,
      671,  672,  692,  682,  681,  712,  923,  711,  944,  694,
      698,  691,  691,  717,  724,  702,  718,  707,  708,  739,
      709,  710,  726,    0,    0,  730,  743,  927,  725,  729,
      743,  743,  743,  763,  924,  751,  755,  741,  754,  746,
      748,  765,  780,  755,  755,  771,  774,  773,  777,  766,

      780,  772,  769,  800,  944,  920,  773,  775,  794,  791,
      919,  928,  815,  781,    0,    0,  816,  817,  920,  829,
      832,  803,  800,    0,  817,    0,    0,  820,  823,  804,
      824,  811,    0,    0,  944,  842,  845,  830,  944,  833,
      814,  834,  821,  944,  944,  916,  823,  944,  834,  841,
      915,    0,  856,  924,  859,  916,  869,  915,    0,  838,
        0,  849,    0,  880,  854,    0,  944,  944,  882,  859,
      944,  911,  944,  859,  869,  910,  919,    0,    0,  885,
      918,    0,  944,  907,  944,  944,  906,  915,  904,  903,
      902,  901,  900,  896,  894,  893,  892,  891,  890,  889,

      888,  885,  884,  880,  879,  878,  876,  743,  646,  621,
      538,  513,  427,  409,  407,  399,  395,  353,  332,  295,
      278,  248,  245,  244,  207,  206,  178,  152,  150,  140,
      106,  102,   70,    0,  944,  944,  909,   78
    } ;

static yyconst flex_int16_t yy_def[439] =
    {   0,
      436,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,  436,  436,  436,  436,  437,  436,  436,  436,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,   36,   15,  436,  436,  436,  436,  436,  436,
      436,  437,  436,  436,  436,  436,  436,  436,  436,   15,
      436,  436,  436,  436,  436,  436,  436,  438,  438,  438,
      436,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,

      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,   70,  436,  436,  436,  436,  436,  436,  436,
      436,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,

      436,  436,  436,  436,  436,  436,  436,  436,  436,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  438,  438,  436,  436,  438,  438,
      438,  438,  438,  436,  436,  438,  438,  438,  438,  438,
      438,  436,  436,  436,  436,  436,  436,  436,  436,  436,

      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      438,  436,  436,  438,  438,  438,  438,  436,  436,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  438,
      438,  438,  438,  438,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      438,  438,  436,  436,  436,  436,  436,  436,  438,  438,
      438,  438,  438,  438,  438,  438,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  438,  436,  438,  438,  436,
      436,  438,  436,  436,  436,  436,  438,  436,  436,  438,
      436,  438,  436,  438,  436,  438,  436,  438,  436,  438,

      436,  438,  436,  438,  436,  438,  436,  438,  436,  438,
      436,  438,  436,  438,  436,  438,  436,  438,  436,  438,
      436,  438,  436,  438,  436,  438,  436,  438,  436,  438,
      436,  438,  436,  438,  436,    0,  436,  436
    } ;

static yyconst flex_int16_t yy_nxt[1007] =
    {   0,
       14,   15,   16,   14,   17,   18,   14,   19,   20,   19,
       21,   22,   14,   21,   23,   24,   21,   25,   26,   27,
       21,   28,   29,   30,   31,   32,   33,   34,   21,   35,
       36,   21,   37,   38,   21,   21,   39,   21,   23,   24,
       21,   25,   26,   27,   21,   28,   29,   30,   31,   32,
       33,   34,   21,   35,   36,   21,   37,   38,   21,   21,
       39,   14,   40,   40,   41,   41,   43,   43,  141,   44,
       44,   82,   97,  150,   98,  142,   42,   42,   45,   78,
      151,  435,   83,  101,   45,   48,   40,   40,   41,   41,
       43,   43,   48,   44,   44,   82,   97,   46,   98,   47,

       42,   42,   45,   46,   49,   47,   83,  101,   45,   48,
       50,   49,   51,  434,  108,  109,   48,  433,   52,   53,
      117,   46,   50,   47,   51,  141,   99,   46,   49,   47,
       52,   53,  142,  118,   50,   49,   51,   79,  108,  109,
      100,   80,   52,   53,  117,   64,   50,  277,   51,   65,
       99,  432,  278,  119,   52,   53,   54,  118,  120,   66,
       80,  431,   80,  430,  100,   80,  102,   88,   84,   58,
       89,   85,   55,   56,   86,  103,   57,  119,   87,  108,
       58,   59,  120,   66,   80,   60,   80,   81,   61,  429,
      102,   88,   84,   58,   89,   85,   55,   56,   86,  103,

       57,  277,   87,  108,   58,   59,  278,  119,  124,   60,
       97,  125,   61,   68,  207,   69,  129,  428,  427,  121,
       70,  208,   94,  130,  137,   71,   95,   72,  139,   73,
       56,  119,  124,   57,   97,  125,   96,   74,   75,  144,
      129,   76,   60,  121,  145,   61,   94,  130,  137,   71,
       95,   72,  139,   73,   56,  426,  425,   57,  109,  424,
       96,   74,   75,  144,  123,   76,   60,  138,  145,   61,
       90,   65,   91,   77,   92,   93,  104,   84,  147,  105,
       85,  106,  109,   86,  107,  150,  258,   87,  123,  423,
      143,   58,  151,  259,   90,  149,   91,   70,   92,   93,

      104,   84,  147,  105,   85,  106,  422,   86,  107,  110,
       84,   87,  153,   85,  436,   58,   86,   99,  111,  149,
       87,  125,  112,  113,  146,  154,  114,  115,  116,   84,
      122,  100,   85,  110,   84,   86,  153,   85,  436,   87,
       86,   99,  111,  421,   87,  125,  112,  113,  146,  154,
      114,  115,  116,   84,  122,  100,   85,  126,  131,   86,
      133,  127,  128,   87,  420,   64,  132,  131,  155,  134,
      156,  159,  148,  160,  135,  132,  163,  161,  136,   66,
      157,  126,  131,  162,  133,  127,  128,  164,  158,   58,
      132,  131,  155,  134,  156,  159,  148,  160,  135,  132,

      163,  161,  136,   66,  157,  165,  419,  162,  168,  169,
      418,  164,  158,   58,   68,  207,   69,  172,  417,  152,
      416,  166,  208,   80,  173,  174,   71,  170,  175,  165,
       55,   56,  168,  169,   57,  167,  171,  178,  415,   75,
      179,  172,   80,   60,   80,  166,   61,   80,  173,  174,
       71,  170,  175,  176,   55,   56,  180,  181,   57,  167,
      171,  178,  177,   75,  179,  182,   80,   60,   80,   81,
       61,  184,  185,  186,   77,  187,  188,  176,  183,  189,
      180,  181,  190,  191,  192,  193,  177,  194,  195,  182,
      196,  197,  198,  200,  138,  184,  185,  186,  201,  187,

      188,  203,  183,  189,  204,  199,  190,  191,  192,  193,
      205,  194,  195,  206,  196,  197,  198,  200,   58,  209,
      211,  212,  201,  210,  414,  203,  214,   80,  204,  199,
      215,  216,  217,  218,  205,  219,  220,  206,  213,  221,
      222,  223,   58,  209,  211,  212,   80,  224,   80,  413,
      214,   80,  225,  226,  215,  216,  217,  218,  227,  219,
      220,  228,  213,  221,  222,  223,  231,  229,  232,  233,
       80,  224,   80,   81,  234,  235,  225,  226,  230,  236,
      237,  238,  227,  239,  241,  228,  242,  243,  240,  244,
      231,  229,  232,  233,  245,  246,  247,  248,  234,  235,

      249,  250,  230,  236,  237,  238,  251,  239,  241,  252,
      242,  243,  240,  244,  253,  256,  260,  254,  245,  246,
      247,  248,  255,  261,  249,  250,  262,  263,  265,  266,
      251,  264,  412,  252,  267,   80,  268,  269,  253,  256,
      260,  254,  270,  271,  272,  273,  255,  261,  274,  275,
      262,  263,  265,  266,   80,  276,   80,  411,  267,   80,
      268,  269,  279,  280,  281,  282,  270,  271,  272,  273,
      283,  286,  274,  275,  287,  284,  288,  289,   80,  276,
       80,   81,  285,  290,  291,  292,  279,  280,  281,  282,
      293,  294,  295,  296,  283,  286,  297,  284,  287,  298,

      288,  289,  299,  300,  285,  301,  302,  290,  291,  292,
      303,  307,  258,  304,  293,  294,  295,  296,  305,  259,
      297,  308,  309,  298,  310,  312,  299,  300,  311,  301,
      302,  314,   80,  315,  303,  307,  313,  316,  317,  320,
      318,  321,  322,  323,  277,  308,  309,  319,  310,  278,
      324,   80,  325,   80,  410,  314,   80,  315,  326,  327,
      328,  316,  317,  320,  284,  321,  322,  323,  329,  330,
      331,  285,  332,  333,  324,   80,  325,   80,   81,  334,
      335,  318,  326,  327,  328,  336,  337,  338,  319,  339,
      340,  341,  329,  330,  331,  342,  332,  333,  343,  344,

      345,  304,  347,  334,  335,  348,  305,  349,  350,  336,
      337,  338,  352,  339,  340,  341,  312,  353,  318,  342,
      359,  360,  343,  344,  345,  319,  347,  313,  354,  348,
      355,  349,  350,  357,  361,  362,  352,  356,  363,  364,
      358,  365,  366,  355,  359,  360,  357,  367,  368,  369,
      356,  370,  371,  358,  373,  374,  375,  353,  361,  362,
      355,  378,  363,  364,  379,  365,  366,  356,  354,  382,
      357,  367,  368,  369,  383,  370,  371,  358,  373,  374,
      375,  380,  385,  380,  386,  378,  380,  409,  379,  408,
      407,  406,  381,  382,  381,  405,  404,  381,  383,  403,

      402,  401,  400,  399,  398,  397,  385,  396,  386,   62,
       62,  395,  394,  393,  392,  391,  388,  390,  389,  388,
      377,  387,  384,  358,  356,  377,  376,  372,  319,  312,
      351,  346,  285,  278,  306,  257,  436,  202,  140,   63,
       67,   63,  436,   13,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,

      436,  436,  436,  436,  436,  436
    } ;

static yyconst flex_int16_t yy_chk[1007] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    3,    4,    5,    6,   69,    5,
        6,   23,   28,   77,   29,   69,    3,    4,    7,  438,
       77,  433,   23,   31,    8,    9,    3,    4,    3,    4,
        5,    6,   10,    5,    6,   23,   28,    7,   29,    7,

        3,    4,    7,    8,    9,    8,   23,   31,    8,    9,
       11,   10,   11,  432,   34,   35,   10,  431,   11,   11,
       37,    7,   12,    7,   12,  141,   30,    8,    9,    8,
       12,   12,  141,   38,   11,   10,   11,   22,   34,   35,
       30,   22,   11,   11,   37,   18,   12,  226,   12,   18,
       30,  430,  226,   39,   12,   12,   15,   38,   40,   18,
       22,  429,   22,  428,   30,   22,   32,   25,   24,   18,
       25,   24,   15,   15,   24,   32,   15,   39,   24,   42,
       15,   15,   40,   18,   22,   15,   22,   22,   15,  427,
       32,   25,   24,   18,   25,   24,   15,   15,   24,   32,

       15,  246,   24,   42,   15,   15,  246,   47,   53,   15,
       50,   55,   15,   20,  148,   20,   57,  426,  425,   50,
       20,  148,   27,   58,   61,   20,   27,   20,   66,   20,
       20,   47,   53,   20,   50,   55,   27,   20,   20,   71,
       57,   20,   20,   50,   72,   20,   27,   58,   61,   20,
       27,   20,   66,   20,   20,  424,  423,   20,   52,  422,
       27,   20,   20,   71,   52,   20,   20,   65,   72,   20,
       26,   65,   26,   20,   26,   26,   33,   41,   74,   33,
       41,   33,   52,   41,   33,  150,  203,   41,   52,  421,
       70,   65,  150,  203,   26,   76,   26,   70,   26,   26,

       33,   41,   74,   33,   41,   33,  420,   41,   33,   36,
       45,   41,   83,   45,   70,   65,   45,   51,   36,   76,
       45,   73,   36,   36,   73,   85,   36,   36,   36,   48,
       51,   51,   48,   36,   45,   48,   83,   45,   70,   48,
       45,   51,   36,  419,   45,   73,   36,   36,   73,   85,
       36,   36,   36,   48,   51,   51,   48,   56,   59,   48,
       60,   56,   56,   48,  418,   64,   59,   75,   86,   60,
       86,   88,   75,   89,   60,   75,   92,   90,   60,   64,
       87,   56,   59,   90,   60,   56,   56,   93,   87,   64,
       59,   75,   86,   60,   86,   88,   75,   89,   60,   75,

       92,   90,   60,   64,   87,   95,  417,   90,   98,  101,
      416,   93,   87,   64,   68,  207,   68,  104,  415,   79,
      414,   97,  207,   79,  105,  106,   68,  103,  107,   95,
       68,   68,   98,  101,   68,   97,  103,  110,  413,   68,
      111,  104,   79,   68,   79,   97,   68,   79,  105,  106,
       68,  103,  107,  109,   68,   68,  112,  113,   68,   97,
      103,  110,  109,   68,  111,  115,   79,   68,   79,   79,
       68,  116,  117,  118,   68,  125,  126,  109,  115,  127,
      112,  113,  128,  129,  130,  131,  109,  132,  133,  115,
      134,  135,  136,  137,  138,  116,  117,  118,  139,  125,

      126,  144,  115,  127,  145,  136,  128,  129,  130,  131,
      146,  132,  133,  147,  134,  135,  136,  137,  138,  149,
      153,  155,  139,  152,  412,  144,  156,  152,  145,  136,
      159,  160,  161,  162,  146,  163,  164,  147,  155,  165,
      166,  167,  138,  149,  153,  155,  152,  169,  152,  411,
      156,  152,  170,  171,  159,  160,  161,  162,  172,  163,
      164,  173,  155,  165,  166,  167,  176,  175,  177,  178,
      152,  169,  152,  152,  179,  180,  170,  171,  175,  181,
      182,  183,  172,  186,  187,  173,  188,  189,  186,  190,
      176,  175,  177,  178,  191,  192,  193,  194,  179,  180,

      195,  196,  175,  181,  182,  183,  197,  186,  187,  198,
      188,  189,  186,  190,  199,  201,  204,  200,  191,  192,
      193,  194,  200,  205,  195,  196,  206,  209,  211,  213,
      197,  210,  410,  198,  215,  210,  216,  217,  199,  201,
      204,  200,  218,  219,  220,  222,  200,  205,  223,  224,
      206,  209,  211,  213,  210,  225,  210,  409,  215,  210,
      216,  217,  228,  229,  230,  231,  218,  219,  220,  222,
      232,  234,  223,  224,  236,  233,  237,  238,  210,  225,
      210,  210,  233,  239,  240,  241,  228,  229,  230,  231,
      242,  243,  244,  245,  232,  234,  248,  249,  236,  250,

      237,  238,  251,  252,  249,  253,  254,  239,  240,  241,
      255,  260,  258,  256,  242,  243,  244,  245,  256,  258,
      248,  261,  262,  250,  263,  265,  251,  252,  264,  253,
      254,  266,  264,  267,  255,  260,  265,  268,  269,  271,
      270,  272,  273,  276,  277,  261,  262,  270,  263,  277,
      279,  264,  280,  264,  408,  266,  264,  267,  281,  282,
      283,  268,  269,  271,  284,  272,  273,  276,  286,  287,
      288,  284,  289,  290,  279,  264,  280,  264,  264,  291,
      292,  293,  281,  282,  283,  294,  295,  296,  293,  297,
      298,  299,  286,  287,  288,  300,  289,  290,  301,  302,

      303,  304,  307,  291,  292,  308,  304,  309,  310,  294,
      295,  296,  314,  297,  298,  299,  313,  317,  318,  300,
      322,  323,  301,  302,  303,  318,  307,  313,  317,  308,
      320,  309,  310,  321,  325,  328,  314,  320,  329,  330,
      321,  331,  332,  336,  322,  323,  337,  338,  340,  341,
      336,  342,  343,  337,  347,  349,  350,  353,  325,  328,
      355,  360,  329,  330,  362,  331,  332,  355,  353,  365,
      357,  338,  340,  341,  370,  342,  343,  357,  347,  349,
      350,  364,  374,  369,  375,  360,  380,  407,  362,  406,
      405,  404,  364,  365,  369,  403,  402,  380,  370,  401,

      400,  399,  398,  397,  396,  395,  374,  394,  375,  437,
      437,  393,  392,  391,  390,  389,  388,  387,  384,  381,
      377,  376,  372,  358,  356,  354,  351,  346,  319,  312,
      311,  306,  285,  278,  257,  202,  143,  140,   67,   62,
       19,   17,   13,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  436,  436,  436,  436,  436,  436,

      436,  436,  436,  436,  436,  436
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 1;

static yyconst flex_int16_t yy_rule_linenum[66] =
    {   0,
      115,  116,  117,  118,  119,  120,  121,  127,  133,  134,
      135,  136,  137,  138,  139,  140,  141,  142,  143,  145,
      146,  147,  148,  150,  151,  152,  153,  154,  155,  156,
      157,  158,  159,  160,  161,  163,  164,  165,  166,  167,
      168,  169,  170,  173,  174,  175,  176,  179,  180,  181,
      182,  183,  184,  186,  187,  189,  190,  191,  192,  195,
      199,  204,  205,  206,  207
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
/*
 *  Copyright (C) 2009 Cedric ISSALY
 *  Copyright (C) 2016 Sauro Menna
 *
 *	This file is part of OCSort.
 *
 *  OCSort is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  OCSort is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with OCSort.  If not, see <http://www.gnu.org/licenses/>.

*/
#line 22 "scanner.l"
  #include <stdio.h>
  #include <stdlib.h>
  #ifndef _MSC_VER
	  #define _strdup strdup
	  #include "utils.h"
	  #define xstrtoll   strtoll
  #else
	  #include <io.h>
	  #define isatty _isatty
	  #define fileno _fileno
	  #define xstrtoll    _strtoi64
  #endif
  #include "ocsort.h"
  #include "parser.h"
  char * pEnd;
  int    nPhase = 0;
  void yyerror(const char *error) {
	printf("Error : %s\n",error);
	if(yytext != NULL) {
		printf("Error near element : %s\n", yytext);
		printf("Token  : %s\n", szMexToken);
	}
} 
#define YY_NO_INPUT
/* for position and length */
/* for value, example condition */
/* sign for numeric values */
/* string */
/* File type */
/*  Format Type Field   */
/* CH|BI|FI|FL|PD|ZD|TI|OT|CTO|LI|OL|CLO|CST|LS|CSL */
/*  CH  Char            
BI  Unsigned Binary
FI  Signed Binary
Fl  Floating Point
PD  Packed
LI / OL / CLO Signed Numeric - sign lealing 
CST Signed Numeric - trailing separate sign
LS / CSL Signed Numeric - leading separate sign
FS / CSF Signed Numeric - with optional leading floating sign  (PIC +++9, PIC ----,...)
*/
/* FORMATTYPE	 CH|BI|FI|FL|PD|ZD|CLO|CST|CSL */
/* extended FORMATTYPE	 CH|BI|FI|FL|PD|ZD|TI|OT|CTO|LI|OL|CLO|CST|LS|CSL */
/*  Char Type  for condition CharType = C(char) | X(hexdical) <String>    */
/*  Char Type  CharType = C(char) | X(hexdical) |Z(zero binary) <String>    */
/*  Order A = Ascending, D = Descending */
/*  Key Tye for indexed file P=Primary, A= ALternative, AD = Alternative with duuplicates, C = Continue */
/* Fixed record */
/* Variable record */
/* comment for occursfill */ 
/* ntimes X,Z,C */
/* Operator condition */ 
/* OCCURFILL   [0-9]{1,5}[C|X|Z]{1} */
/* <CHSC>{CHARTYPE} */
/* <ORDK>{ORDER} */
/* <KEYV>{KEYTYPE} */





#line 997 "scanner.c"

#define INITIAL 0
#define KEYV 1
#define ORDK 2
#define CHSC 3
#define TCOND 4
#define TORG 5

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */

static int yy_init_globals (void );

/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* %if-bison-bridge */
/* %endif */

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

/* %not-for-header */

/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */

/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\
/* %if-c++-only C++ definition \ */\
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */

/* %ok-for-header */

/* %not-for-header */

/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */

extern int yylex (void);

#define YY_DECL int yylex (void)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %not-for-header */

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
/* %% [7.0] user's declarations go here */
#line 113 "scanner.l"


#line 1233 "scanner.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
/* %if-c-only */
			yyin = stdin;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! yyout )
/* %if-c-only */
			yyout = stdout;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 437 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 436 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 66 )
				fprintf( stderr, "--accepting rule at line %ld (\"%s\")\n",
				         (long)yy_rule_linenum[yy_act], yytext );
			else if ( yy_act == 66 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         yytext );
			else if ( yy_act == 67 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 115 "scanner.l"
return BUILD;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 116 "scanner.l"
BEGIN(TCOND);   return COND; 
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 117 "scanner.l"
return COPY; 
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 118 "scanner.l"
return COPY; 
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 119 "scanner.l"
return TOKSKIP;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 120 "scanner.l"
return ENDREC;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 121 "scanner.l"
if (nPhase == 1) { 
                                BEGIN(ORDK);  
                                nPhase = 0; 
                            }else {	
                                BEGIN(CHSC); 
                            } return FIELDS; 
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 127 "scanner.l"
if (nPhase == 1) { 
                                BEGIN(ORDK);  
                                nPhase = 0; 
                            }else {	
                                BEGIN(CHSC); 
                           } return FIELDS; 
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 133 "scanner.l"
return FNAMES; //return FILES;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 134 "scanner.l"
return FNAMES;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 135 "scanner.l"
return FORMAT;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 136 "scanner.l"
BEGIN(INITIAL); return GIVE;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 137 "scanner.l"
BEGIN(TCOND);   return INCLUDE; 
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 138 "scanner.l"
BEGIN(CHSC);    return INREC;		
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 139 "scanner.l"
BEGIN(KEYV);    return KEY;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 140 "scanner.l"
nPhase = 1;  BEGIN(INITIAL); return MERGE;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 141 "scanner.l"
return NONE;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 142 "scanner.l"
BEGIN(TCOND);   return OMIT; 
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 143 "scanner.l"
return OPTION;
	YY_BREAK
/*"ORG"		                                    return ORG;*/
case 20:
YY_RULE_SETUP
#line 145 "scanner.l"
BEGIN(TORG);                return ORG;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 146 "scanner.l"
return OUTFIL;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 147 "scanner.l"
return OUTFIL;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 148 "scanner.l"
BEGIN(CHSC);    return OUTREC;		
	YY_BREAK
/* "RECORD"	                         return RECORD; */
case 24:
YY_RULE_SETUP
#line 150 "scanner.l"
BEGIN(INITIAL); return RECORD;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 151 "scanner.l"
return SAVE;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 152 "scanner.l"
return SKIPREC;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 153 "scanner.l"
nPhase = 1;  BEGIN(INITIAL); return SORT;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 154 "scanner.l"
return STARTREC;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 155 "scanner.l"
return STOPAFT;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 156 "scanner.l"
return SPLIT;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 157 "scanner.l"
return SPLITBY;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 158 "scanner.l"
return SUM;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 159 "scanner.l"
BEGIN(INITIAL); return USE;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 160 "scanner.l"
return VLSCMP;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 161 "scanner.l"
return VLSHRT;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 163 "scanner.l"
printf("OCSort - Warning - Token skipped : "); ECHO; printf("\n"); // return TOKSKIP;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 164 "scanner.l"
printf("OCSort - Warning - Token skipped : "); ECHO; printf("\n"); // return TOKSKIP;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 165 "scanner.l"
printf("OCSort - Warning - Token skipped : "); ECHO; printf("\n"); // return TOKSKIP;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 166 "scanner.l"
printf("OCSort - Warning - Token skipped : "); ECHO; printf("\n"); // return TOKSKIP;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 167 "scanner.l"
printf("OCSort - Warning - Token skipped : "); ECHO; printf("\n"); // return TOKSKIP; 
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 168 "scanner.l"
printf("OCSort - Warning - Token skipped : "); ECHO; printf("\n"); // return TOKSKIP; 
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 169 "scanner.l"
printf("OCSort - Warning - Token skipped : "); ECHO; printf("\n"); // return TOKSKIP; 
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 170 "scanner.l"
printf("OCSort - Warning - Token skipped : "); ECHO; printf("\n"); // return TOKSKIP; 
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 173 "scanner.l"
return AND;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 174 "scanner.l"
return AND;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 175 "scanner.l"
return OR;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 176 "scanner.l"
return OR;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 179 "scanner.l"
yylval.string = _strdup(yytext) ;					return OPCOND; 	
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 180 "scanner.l"
yylval.string = _strdup(yytext) ;					return ORDER; 
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 181 "scanner.l"
yylval.number = strtol(yytext, &pEnd, 10) ;			return DIGIT;  
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 182 "scanner.l"
yylval.number = strtol(yytext, &pEnd, 10) ;			return DIGIT; 
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 183 "scanner.l"
yylval.llnumber = xstrtoll(yytext, &pEnd, 10) ;		return SIGNDIGITBIG;  
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 184 "scanner.l"
yylval.llnumber = xstrtoll(yytext, &pEnd, 10) ;		return SIGNDIGITBIG;  
	YY_BREAK
/* {FORMATTYPE}		        yylval.string = _strdup(yytext) ;                   return FORMATTYPE;  */
case 54:
YY_RULE_SETUP
#line 186 "scanner.l"
yylval.string = _strdup(yytext) ;                   return RECTYPEFIX;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 187 "scanner.l"
yylval.string = _strdup(yytext) ;                   return RECTYPEVAR;
	YY_BREAK
/* {FILETYPE}   	            yylval.string = _strdup(yytext) ;                   return FILETYPE;  */ 
case 56:
YY_RULE_SETUP
#line 189 "scanner.l"
yylval.string = _strdup(yytext) ;                   return FILETYPE; 
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 190 "scanner.l"
yylval.string = _strdup(yytext) ;                   return OCCURFILL;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 191 "scanner.l"
yylval.string = _strdup(yytext) ;                   return CHARTCOND;    
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 192 "scanner.l"
yylval.string = _strdup(yytext) ;                   return CHARTYPE; 
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 195 "scanner.l"
yylval.string = _strdup(yytext) ;                   return FORMATTYPE;  
	YY_BREAK
/* String C''';'   */
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 199 "scanner.l"
{yylval.string=malloc(strlen(yytext)-1);
					 memcpy(yylval.string,yytext+1,strlen(yytext)-2);
					 yylval.string[strlen(yytext)-2]=0;
					 return STRING;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 204 "scanner.l"
yylval.string = _strdup(yytext) ; return KEYTYPE; 
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 205 "scanner.l"
yylval.string = _strdup(yytext) ; return STRING;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 206 "scanner.l"

	YY_BREAK
case 65:
YY_RULE_SETUP
#line 207 "scanner.l"
return yytext[0];
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 210 "scanner.l"
ECHO;
	YY_BREAK
#line 1692 "scanner.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(KEYV):
case YY_STATE_EOF(ORDK):
case YY_STATE_EOF(CHSC):
case YY_STATE_EOF(TCOND):
case YY_STATE_EOF(TORG):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */

/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
static int yy_get_next_buffer (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */

    static yy_state_type yy_get_previous_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 437 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 437 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 436);

		return yy_is_jam ? 0 : yy_current_state;
}

/* %if-c-only */

/* %endif */

/* %if-c-only */
#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

/* %endif */
/* %if-c++-only */
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and yylineno */

	return c;
}
/* %if-c-only */
#endif	/* ifndef YY_NO_INPUT */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
    void yyrestart  (FILE * input_file )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
static void yy_load_buffer_state  (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
/* %if-c-only */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )
/* %endif */
/* %if-c++-only */
/* %endif */

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
/* %endif */
/* %if-c++-only */
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
void yypop_buffer_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
static void yyensure_buffer_stack (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}
/* %endif */

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}
/* %endif */
/* %if-c++-only */
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/* %if-reentrant */
/* %endif */

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

/* %if-reentrant */
/* %endif */
    return 0;
}
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 210 "scanner.l"


