# for cygwin
# htdocs=/srv/www/htdocs
htdocs=/var/www/vhosts/wortfee.net/httpdocs

all:	p001_wortfee_js

p001_wortfee_js:
# js
	cp herbyCookie.min.js $(htdocs)/js/herbyCookie.min.js
	cp jquery.countdown.js $(htdocs)/js/jquery.countdown.js
	cp jquery.validate.min.js $(htdocs)/js/jquery.validate.min.js
	cp jquery-3.3.1.min.js $(htdocs)/js/jquery-3.3.1.min.js
	cp p001_wortfee.js $(htdocs)/js/p001_wortfee.js
	
clean:
# js
	rm -f $(htdocs)/js/herbyCookie.min.js
	rm -f $(htdocs)/js/jquery.countdown.js
	rm -f $(htdocs)/js/jquery.validate.min.js
	rm -f $(htdocs)/js/jquery-3.3.1.min.js
	rm -f $(htdocs)/js/p001_wortfee.js
   