# for cygwin
# htdocs=/srv/www/htdocs
htdocs=/var/www/vhosts/wortfee.net/httpdocs

all:	p001_wortfee_img_wortfee

p001_wortfee_img_wortfee:
# wortfee images
	cp -r ../img_wortfee $(htdocs)/img_wortfee
	
clean:
# wortfee images
	rm -fr $(htdocs)/img_wortfee
    