#line 2 "..\\..\\scanner.c"

#line 4 "..\\..\\scanner.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */

/* %if-c-only */
/* %if-not-reentrant */

/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
/* %endif */

/* %if-c-only */
    
/* %endif */

/* %if-c-only */

/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* %if-c++-only */
/* %endif */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* %not-for-header */

/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

/* %if-not-reentrant */
extern yy_size_t yyleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
extern FILE *yyin, *yyout;
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
	FILE *yy_input_file;
/* %endif */

/* %if-c++-only */
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

/* %if-not-reentrant */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */

/* %if-not-reentrant */
/* %not-for-header */

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;
/* %ok-for-header */

/* %endif */

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

/* %endif */

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */

#define yywrap() 1
#define YY_SKIP_YYWRAP

#define FLEX_DEBUG

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

/* %if-c-only Standard (non-C++) definition */

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;

/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 91
#define YY_END_OF_BUFFER 92
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[564] =
    {   0,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   92,   90,   89,   91,   90,   90,   90,   90,
       88,   73,   88,   88,   88,   88,   77,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       78,   88,   88,   87,   87,   87,   72,   72,   82,   82,
       82,   81,   81,   81,   88,   88,   88,   88,   89,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       86,    0,    0,    0,   74,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   88,   73,   80,   80,   84,
       88,   84,   88,   88,   88,   88,   88,   88,   88,   71,

       88,   83,   84,   84,   88,   88,   71,   88,   71,   88,
       88,   88,   71,   71,   88,   88,   71,   88,   88,   88,
       88,   88,   88,   88,   84,   88,   88,   88,   88,   88,
       71,   88,   88,   88,   88,   88,   88,   88,   84,   87,
       79,   79,   79,   79,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   74,    0,   68,    0,    0,    0,    0,    0,
        0,    0,    0,   70,   73,   88,   88,   84,   88,   88,
       84,   84,   88,   85,    8,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   26,   88,   88,   88,   88,

       88,   88,   88,   88,   88,   88,   33,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   53,   88,
       88,   55,   88,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   79,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   74,    0,    0,    0,    0,    0,   69,
        0,   73,   88,   88,    5,   88,    7,   88,   88,   88,
       88,   88,   18,    3,   88,   88,   22,   88,   88,   47,
       88,   88,   40,   88,   88,   30,   88,   31,   46,   88,
       88,   88,   88,   88,   88,   88,   37,   88,   42,   88,

       88,   88,   88,   88,   88,   88,   88,    0,   18,    3,
        0,    0,    0,    0,   40,   30,   31,    0,   37,    0,
        0,    0,    0,    0,    0,    0,    0,   74,    0,   67,
        0,    0,    0,    0,   73,    1,   88,   88,   14,   15,
       16,   17,   88,   88,   88,   88,   18,   18,   19,    3,
        3,   88,   88,   88,   24,   88,   88,   28,   88,   88,
       30,   30,   88,   88,   88,   88,   88,   88,   88,   88,
       37,   37,   88,   88,   51,   88,   88,    0,   54,   88,
       88,   88,   88,    0,   19,    0,    0,    0,    0,    0,
        0,   51,    0,    0,    0,    0,    0,    0,    6,   74,

        0,    0,    0,    0,   75,    1,    1,    2,   88,    9,
       63,   39,   11,   19,   19,   20,   21,   88,   88,   88,
       88,   88,   88,   32,   34,   25,   88,   41,   88,   88,
       88,   43,   88,   88,   88,   54,   88,   56,   57,   58,
        9,   20,   21,    0,    0,   36,    0,    0,    0,    0,
       56,   57,   58,   76,    0,   64,    0,    0,   75,    2,
        2,   61,    0,   10,   20,   20,   21,   21,   23,   88,
        0,   27,   88,    4,   44,   35,   13,   88,   88,   38,
       88,   88,   50,   88,   23,   38,    0,    0,   50,   76,
       62,    0,    0,   75,   10,   29,   27,   65,    4,    4,

        0,   12,   48,   59,    0,   52,   49,   45,   49,   76,
       66,   60,   75,   12,   52,   76,   75,   76,   75,   76,
       75,   76,   75,   76,   75,   76,   75,   76,   75,   76,
       75,   76,   75,   76,   75,   76,   75,   76,   75,   76,
       75,   76,   75,   76,   75,   76,   75,   76,   75,   76,
       75,   76,   75,   76,   75,   76,   75,   76,   75,   76,
       75,   76,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    4,    5,    6,
        7,    1,    8,    9,   10,   11,    1,   12,   13,   14,
       15,   16,   17,   12,   12,   12,   12,    1,    1,    1,
       18,    1,    1,    1,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   11,   41,   42,   43,
        1,    1,    1,    1,   11,    1,   44,   45,   46,   47,

       48,   49,   50,   51,   52,   53,   54,   55,   56,   57,
       58,   59,   60,   61,   62,   63,   64,   65,   11,   66,
       67,   68,    1,   69,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[70] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        2,    2,    2,    2,    2,    2,    2,    1,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    1
    } ;

static yyconst flex_int16_t yy_base[566] =
    {   0,
        0,    0,   51,   52,   55,   56,   63,   71,   80,   86,
       88,  108,  736, 1510,  169, 1510,  728,  159,  142,  235,
        0,  293,  146,  157,   61,  228,  285,  226,   51,   55,
       68,  141,  118,  149,  332,   72,  100,  379,  100,  284,
      148,  614,  166,  173,  293,  200,    0,  204,  294,    0,
      208,  344,    0,  611,  229,  342,  299,  197,    0,  219,
      382,  271,  290,  292,  299,  336,  391,  303,  558,  565,
     1510,  425,  420,  302,  370,  428,   80,  392,  321,  370,
      416,  378,  427,  396,  166,    0,  486,    0, 1510,    0,
      404,  434,  422,  430,  429,  427,  510,  507,  446,  430,

      434,    0,  481,    0,  462,  460,    0,  465,    0,  486,
      481,  467,  478,    0,  476,  491,    0,  494,  487,  485,
      479,  493,  481,  497,    0,  528,  483,  501,  510,  524,
        0,  536,  526,  524,  526,  538,  525,  575,    0,    0,
        0,  539,    0,    0,  542,  535,  547,  531,  547,  541,
      553,  544,  551,  543,  559,  575,  574,  586,  570,  574,
      621,  576,  633,  172, 1510,  466,  589,  594,  592,  630,
      175,  623,  226, 1510,  645,  625,  631,    0,  642,  623,
        0,    0,  643,    0,  631,  649,  636,  640,  651,  640,
      641,  650,  645,  653,  651,    0,  659,  660,  649,  664,

      683,  680,  681,  667,  671,  687,    0,  695,  679,  683,
      684,  685,  697,  687,  684,  696,  688,  691,    0,  703,
      713,    0,  732,    0,    0,    0,  715,    0,    0,    0,
        0,    0,    0,    0,    0,  699,  731,  706,  721,  725,
      738,  727,  742,  728,  731,  745,  735,  743,  735,  738,
      755,  754,  732,  795,  231,  735,  783,  780,  236, 1510,
      771,  801,  783,  794,    0,  797,    0,  808,  802,  796,
      792,  810,  831,  118,  811,  816,    0,  797,  816,  809,
      801,  818,    0,  804,  808,   74,  812,    0,    0,  815,
      822,  829,  823,  818,  819,  818,  271,  829,  846,  832,

      837,  857,  879,  855,  853,  849,  849,  864,  887,  886,
      868,  873,  859,  864, 1510,  472, 1510,  880,  367,  869,
      868,  870,  894,  883,  879,  881,  780,  938,  917, 1510,
      897,  891,  884,  892,  946,  923,  919,  908,    0,    0,
        0,    0,  927,  919,  926,  928,  927,  412,  966,  405,
      964,  933,  933,  950,    0,  951,  950,    0,  958,  957,
      977,  366,  959,  951,  955,  965,  968,  966,  960,  969,
      991,  302,  971,  976,  984,  970,  983, 1007,  299,  978,
      981,  980,  982, 1000, 1024,  985,  986, 1005, 1002, 1009,
     1011, 1015, 1000, 1013, 1004, 1003, 1004, 1049, 1510, 1056,

     1014, 1017, 1038, 1035, 1072,  280, 1046, 1063, 1036,    0,
        0,    0, 1074, 1088,  243, 1089, 1091, 1054, 1036, 1078,
     1067, 1069, 1072,    0, 1081,    0, 1063,    0, 1087, 1086,
     1087,    0, 1067, 1087, 1073,  248, 1089,    0,    0,    0,
     1510, 1112, 1113, 1090, 1121, 1510, 1095, 1075, 1095, 1086,
     1510, 1510, 1510, 1138, 1102, 1510, 1117, 1124, 1144,  244,
     1144,    0, 1145,  240, 1162,  220, 1164,  205,    0, 1130,
     1166,  184, 1142, 1172,    0,    0, 1173, 1138, 1156,    0,
     1176, 1158,    0, 1158, 1510, 1510, 1180, 1160, 1510, 1195,
     1510, 1158, 1168, 1203,  160,    0,  132,    0,  131, 1181,

     1185,  128,    0,    0, 1219,   91,    0,    0, 1510, 1210,
     1510, 1510, 1216,   88,   85, 1226, 1232, 1238, 1244, 1250,
     1256, 1262, 1268, 1274, 1280, 1286, 1292, 1298, 1304, 1310,
     1316, 1322, 1328, 1334, 1340, 1346, 1352, 1358, 1364, 1370,
     1376, 1382, 1388, 1394, 1400, 1406, 1412, 1418, 1424, 1430,
     1436, 1442, 1448, 1454, 1460, 1466, 1472, 1478, 1484, 1490,
        0, 1510, 1510, 1507,   77
    } ;

static yyconst flex_int16_t yy_def[566] =
    {   0,
      563,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,  563,  563,  563,  563,  564,  563,  563,  563,
      565,  565,  565,  565,  565,  565,  565,  565,  565,  565,
      565,  565,  565,  565,  565,  565,  565,  565,  565,  565,
      565,  565,  565,  565,  565,  565,  565,  565,  565,  565,
      565,  565,  565,  565,  565,  565,  565,   38,   15,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  564,
      563,  563,  563,  563,  563,   15,  563,   15,  563,  563,
      563,  563,  563,  563,  563,  565,   22,  565,  563,  565,
      565,  565,  565,  565,  565,  565,  565,  565,  565,  565,

      565,  565,  565,  565,  565,  565,  565,  565,  565,  565,
      565,  565,  565,  565,  565,  565,  565,  565,  565,  565,
      565,  565,  565,  565,  565,  565,  565,  565,  565,  565,
      565,  565,  565,  565,  565,  565,  565,  565,  565,  565,
      565,  565,  565,  565,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,   78,  563,  563,  563,  563,
      563,  563,  563,  563,   22,  565,  565,  565,  565,  565,
      565,  565,  565,  565,  565,  565,  565,  565,  565,  565,
      565,  565,  565,  565,  565,  565,  565,  565,  565,  565,

      565,  565,  565,  565,  565,  565,  565,  565,  565,  565,
      565,  565,  565,  565,  565,  565,  565,  565,  565,  565,
      565,  565,  565,  565,  565,  565,  565,  565,  565,  565,
      565,  565,  565,  565,  565,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,   22,  565,  565,  565,  565,  565,  565,  565,  565,
      565,  565,  565,  565,  565,  565,  565,  565,  565,  565,
      565,  565,  565,  565,  565,  565,  565,  565,  565,  565,
      565,  565,  565,  565,  565,  565,  565,  565,  565,  565,

      565,  565,  565,  565,  565,  565,  565,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,   22,  565,  565,  565,  565,  565,
      565,  565,  565,  565,  565,  565,  563,  563,  565,  563,
      563,  565,  565,  565,  565,  565,  565,  565,  565,  565,
      563,  563,  565,  565,  565,  565,  565,  565,  565,  565,
      563,  563,  565,  565,  565,  565,  565,  563,  563,  565,
      565,  565,  565,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,

      563,  563,  563,  563,  565,  563,  563,  565,  565,  565,
      565,  565,  565,  563,  563,  565,  565,  565,  565,  565,
      565,  565,  565,  565,  565,  565,  565,  565,  565,  565,
      565,  565,  565,  565,  565,  563,  565,  565,  565,  565,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  565,  563,
      563,  565,  563,  563,  563,  563,  563,  563,  565,  565,
      563,  563,  565,  565,  565,  565,  565,  565,  565,  565,
      565,  565,  565,  565,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  565,  563,  565,  563,  565,  563,  563,

      563,  563,  565,  565,  563,  563,  565,  565,  563,  563,
      563,  563,  565,  563,  563,  563,  565,  563,  565,  563,
      565,  563,  565,  563,  565,  563,  565,  563,  565,  563,
      565,  563,  565,  563,  565,  563,  565,  563,  565,  563,
      565,  563,  565,  563,  565,  563,  565,  563,  565,  563,
      565,  563,  565,  563,  565,  563,  565,  563,  565,  563,
      565,  563,    0,  563,  563
    } ;

static yyconst flex_int16_t yy_nxt[1580] =
    {   0,
       14,   15,   16,   14,   17,   18,   14,   19,   20,   19,
       21,   22,   22,   22,   22,   22,   22,   14,   21,   23,
       24,   25,   26,   27,   28,   21,   29,   30,   31,   32,
       33,   34,   35,   36,   21,   37,   38,   39,   40,   41,
       21,   42,   43,   21,   23,   24,   25,   26,   27,   28,
       21,   29,   30,   31,   32,   33,   34,   35,   36,   21,
       37,   38,   39,   40,   41,   21,   42,   43,   14,   44,
       44,   45,   45,   47,   47,  361,   48,   48,   86,   96,
      362,  164,  110,   49,   46,   46,  515,  111,  165,  514,
      112,   49,  515,  125,   44,   44,   45,   45,   47,   47,

       52,   48,   48,   50,   96,   51,   52,  110,   49,   46,
       46,   50,  111,   51,   55,  112,   49,   56,  125,  350,
       53,   54,  126,   57,   58,   52,   53,   54,   50,  514,
       51,   52,  499,  497,   55,  351,   50,   56,   51,   55,
      115,  134,   56,   57,   58,   53,   54,  126,   57,   58,
      116,   53,   54,   75,   75,   75,   75,   75,   75,   55,
       72,  495,   56,  113,   73,  115,  134,  173,   57,   58,
       59,  117,   90,  164,  174,  116,  259,  137,  114,   74,
      165,  118,   92,  260,   91,  497,   93,  139,  113,   94,
       65,   60,   61,   95,  140,   62,  117,   90,   63,   64,

       65,   66,  137,  114,   74,   67,  118,   92,   68,   91,
       69,   93,  139,  468,   94,   65,   60,   61,   95,  140,
       62,  125,   96,   63,   64,   65,   66,  173,  466,  139,
       67,  144,  329,   68,  174,   69,   76,  259,   77,  330,
       97,  495,   98,   78,  260,  460,  125,   96,  107,  436,
      145,  415,  108,   79,  139,   80,  144,   81,   61,   99,
      110,   62,  100,  109,   63,   64,   82,   83,  101,  141,
       84,   67,  371,  107,   68,  145,   69,  108,   79,  372,
       80,  406,   81,   61,   99,  110,   62,  100,  109,   63,
       64,   82,   83,  101,  141,   84,   67,  102,  102,   68,

      436,   69,  149,   85,   87,   87,   87,   87,   87,   87,
      372,  103,  150,   88,  104,  135,  105,  106,   92,   92,
      136,  126,   93,   93,  151,   94,   94,  149,  143,   95,
       95,  152,  159,   88,  162,   88,  103,  150,   88,  104,
      135,  105,  106,   92,   92,  136,  126,   93,   93,  151,
       94,   94,  167,  143,   95,   95,  152,  159,   88,  162,
       88,   89,  119,  120,  113,  121,  153,  122,  371,   92,
      123,  124,  362,   93,  154,  372,   94,  167,  142,  114,
       95,  163,  163,  163,  163,  163,  163,  119,  120,  113,
      121,  153,  122,  166,   92,  123,  124,  127,   93,  154,

       78,   94,  168,  142,  114,   95,  350,  128,  146,  155,
      170,  129,  130,  147,  148,  131,  132,  133,  172,  156,
      348,  161,  127,  563,  157,   73,   72,  168,  158,   76,
      176,   77,  128,  146,  155,  170,  129,  130,  147,  148,
      131,  132,  133,  172,  156,   74,   79,  145,  563,  157,
      169,   65,  177,  158,  178,  176,   65,  153,  181,  563,
       83,  179,  171,  180,  183,  154,  182,  185,  186,  187,
       74,   79,  145,  361,  563,  169,   65,  177,  362,  178,
      190,   65,  153,  181,  563,   83,  179,  171,  180,  183,
      154,  182,  185,  186,  187,  191,   85,  175,  175,  175,

      175,  175,  175,  188,  192,  190,  193,  195,  196,  197,
      189,  198,  199,  204,  205,  200,  206,  207,  208,  209,
      191,  194,  213,  184,  201,  202,  184,  214,  188,  192,
      203,  193,  195,  196,  197,  189,  198,  199,  204,  205,
      200,  206,  207,  208,  209,  215,  194,  213,  210,  201,
      202,  211,  214,  216,  217,  203,  219,  220,  212,  221,
      222,  223,  235,  236,  237,  238,  239,  240,  218,   71,
      215,  160,  241,  210,  242,  243,  211,  244,  216,  217,
      245,  219,  220,  212,  221,  222,  223,  235,  236,  237,
      238,  239,  240,  218,  224,  225,  226,  241,  246,  242,

      243,  247,  244,  248,  249,  245,  251,  252,  227,  253,
      255,  228,  229,  230,  231,  232,  233,  234,  250,  224,
      225,  226,  161,  246,  138,  256,  247,  138,  248,  249,
      257,  251,  252,  227,  253,  255,  228,  229,  230,  231,
      232,  233,  234,  250,  254,  254,  254,  254,  254,  254,
      256,  258,   65,  261,  263,  257,  262,  262,  262,  262,
      262,  262,  264,  265,  267,  268,  269,  270,  271,  272,
      275,  276,  277,  273,  278,  279,  258,   65,  261,  263,
      274,  266,  280,  281,  282,  283,  284,  264,  265,  267,
      268,  269,  270,  271,  272,  275,  276,  277,  273,  278,

      279,  285,  286,  287,  288,  274,  266,  280,  281,  282,
      283,  284,  289,  290,  293,  294,  295,  296,  291,  297,
      298,  299,  300,  301,  302,  303,  285,  286,  287,  288,
      292,  304,   71,  307,  308,  563,  311,  289,  290,  293,
      294,  295,  296,  291,  297,  298,  299,  300,  301,  302,
      303,  312,  305,  309,  313,  292,  304,  306,  307,  308,
      310,  311,  314,  315,  316,  317,  318,  319,  320,  321,
      322,  323,  326,  327,  331,  324,  312,  305,  309,  313,
      325,  398,  306,  563,  563,  310,  399,  314,  315,  316,
      317,  318,  319,  320,  321,  322,  323,  326,  327,  331,

      324,  332,  333,  334,  336,  325,  328,  328,  328,  328,
      328,  328,  335,  335,  335,  335,  335,  335,  337,  338,
      339,  340,  341,  342,  343,  344,  332,  333,  334,  336,
      345,  346,  347,  352,  353,  354,  355,  356,  357,  348,
      358,  359,  563,  337,  338,  360,  363,  364,  365,  343,
      344,  366,  367,  368,  369,  345,  346,  370,  352,  353,
      354,  355,  356,  357,  373,  358,  359,  349,  374,  375,
      360,  363,  364,  365,  376,  377,  366,  367,  368,  369,
      378,  380,  370,  381,  382,  383,  384,  350,  347,  373,
      386,  387,  349,  374,  375,  348,  379,  388,  563,  376,

      377,  389,  390,  351,  391,  392,  380,  393,  381,  382,
      383,  384,  394,  395,  396,  386,  387,  397,  329,  401,
      402,  403,  388,  385,  406,  330,  389,  390,  347,  391,
      392,  404,  393,  563,  563,  348,  563,  394,  395,  396,
      407,  408,  397,  409,  401,  402,  403,  410,  385,  400,
      400,  400,  400,  400,  400,  411,  404,  405,  405,  405,
      405,  405,  405,  412,  413,  350,  408,  414,  409,  416,
      417,  418,  410,  419,  415,  420,  421,  422,  361,  423,
      411,  351,  424,  362,  425,  426,  427,  428,  412,  413,
      429,  430,  371,  431,  416,  417,  418,  432,  419,  372,

      420,  421,  422,  433,  423,  434,  435,  424,  378,  425,
      426,  427,  428,  437,  438,  429,  430,  439,  431,  440,
      441,  442,  432,  443,  379,  414,  444,  445,  433,  446,
      434,  435,  415,  447,  448,  449,  450,  451,  437,  438,
      452,  453,  439,  563,  440,  441,  442,  406,  443,  455,
      398,  444,  445,  456,  446,  399,  457,  458,  447,  448,
      449,  450,  451,  407,  460,  452,  453,  454,  454,  454,
      454,  454,  454,  462,  455,  463,  469,  470,  456,  471,
      461,  457,  458,  459,  459,  459,  459,  459,  459,  414,
      465,  464,  467,  473,  474,  472,  415,  466,  462,  468,

      475,  469,  470,  476,  477,  478,  479,  480,  481,  482,
      483,  484,  485,  465,  467,  486,  487,  488,  473,  474,
      466,  468,  471,  489,  563,  475,  563,  563,  476,  477,
      478,  479,  480,  481,  482,  483,  484,  485,  472,  491,
      486,  487,  488,  492,  493,  460,  463,  563,  489,  490,
      490,  490,  490,  490,  490,  494,  494,  494,  494,  494,
      494,  461,  464,  465,  491,  467,  496,  471,  492,  493,
      466,  498,  468,  499,  501,  503,  504,  505,  507,  508,
      509,  505,  499,  472,  563,  563,  501,  511,  512,  500,
      502,  496,  563,  506,  563,  563,  498,  506,  500,  563,

      503,  504,  502,  507,  508,  509,  510,  510,  510,  510,
      510,  510,  511,  512,  513,  513,  513,  513,  513,  513,
      505,  516,  516,  516,  516,  516,  516,  517,  517,  517,
      517,  517,  517,  563,  563,  563,  506,  518,  518,  518,
      518,  518,  518,  519,  519,  519,  519,  519,  519,  520,
      520,  520,  520,  520,  520,  521,  521,  521,  521,  521,
      521,  522,  522,  522,  522,  522,  522,  523,  523,  523,
      523,  523,  523,  524,  524,  524,  524,  524,  524,  525,
      525,  525,  525,  525,  525,  526,  526,  526,  526,  526,
      526,  527,  527,  527,  527,  527,  527,  528,  528,  528,

      528,  528,  528,  529,  529,  529,  529,  529,  529,  530,
      530,  530,  530,  530,  530,  531,  531,  531,  531,  531,
      531,  532,  532,  532,  532,  532,  532,  533,  533,  533,
      533,  533,  533,  534,  534,  534,  534,  534,  534,  535,
      535,  535,  535,  535,  535,  536,  536,  536,  536,  536,
      536,  537,  537,  537,  537,  537,  537,  538,  538,  538,
      538,  538,  538,  539,  539,  539,  539,  539,  539,  540,
      540,  540,  540,  540,  540,  541,  541,  541,  541,  541,
      541,  542,  542,  542,  542,  542,  542,  543,  543,  543,
      543,  543,  543,  544,  544,  544,  544,  544,  544,  545,

      545,  545,  545,  545,  545,  546,  546,  546,  546,  546,
      546,  547,  547,  547,  547,  547,  547,  548,  548,  548,
      548,  548,  548,  549,  549,  549,  549,  549,  549,  550,
      550,  550,  550,  550,  550,  551,  551,  551,  551,  551,
      551,  552,  552,  552,  552,  552,  552,  553,  553,  553,
      553,  553,  553,  554,  554,  554,  554,  554,  554,  555,
      555,  555,  555,  555,  555,  556,  556,  556,  556,  556,
      556,  557,  557,  557,  557,  557,  557,  558,  558,  558,
      558,  558,  558,  559,  559,  559,  559,  559,  559,  560,
      560,  560,  560,  560,  560,  561,  561,  561,  561,  561,

      561,  562,  562,  562,  562,  562,  562,   70,   70,   13,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563
    } ;

static yyconst flex_int16_t yy_chk[1580] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        4,    3,    4,    5,    6,  286,    5,    6,  565,   25,
      286,   77,   29,    7,    3,    4,  515,   30,   77,  514,
       31,    8,  506,   36,    3,    4,    3,    4,    5,    6,

        9,    5,    6,    7,   25,    7,   10,   29,    7,    3,
        4,    8,   30,    8,   11,   31,    8,   11,   36,  274,
        9,    9,   37,   11,   11,    9,   10,   10,    7,  502,
        7,   10,  499,  497,   12,  274,    8,   12,    8,   11,
       33,   39,   11,   12,   12,    9,    9,   37,   11,   11,
       33,   10,   10,   19,   19,   19,   19,   19,   19,   12,
       18,  495,   12,   32,   18,   33,   39,   85,   12,   12,
       15,   34,   23,  164,   85,   33,  171,   41,   32,   18,
      164,   34,   24,  171,   23,  472,   24,   43,   32,   24,
       18,   15,   15,   24,   44,   15,   34,   23,   15,   15,

       15,   15,   41,   32,   18,   15,   34,   24,   15,   23,
       15,   24,   43,  468,   24,   18,   15,   15,   24,   44,
       15,   46,   48,   15,   15,   15,   15,  173,  466,   51,
       15,   58,  255,   15,  173,   15,   20,  259,   20,  255,
       26,  464,   26,   20,  259,  460,   46,   48,   28,  436,
       60,  415,   28,   20,   51,   20,   58,   20,   20,   26,
       55,   20,   26,   28,   20,   20,   20,   20,   26,   55,
       20,   20,  297,   28,   20,   60,   20,   28,   20,  297,
       20,  406,   20,   20,   26,   55,   20,   26,   28,   20,
       20,   20,   20,   26,   55,   20,   20,   27,   27,   20,

      379,   20,   62,   20,   22,   22,   22,   22,   22,   22,
      372,   27,   63,   22,   27,   40,   27,   27,   45,   49,
       40,   57,   45,   49,   64,   45,   49,   62,   57,   45,
       49,   65,   68,   22,   74,   22,   27,   63,   22,   27,
       40,   27,   27,   45,   49,   40,   57,   45,   49,   64,
       45,   49,   79,   57,   45,   49,   65,   68,   22,   74,
       22,   22,   35,   35,   56,   35,   66,   35,  319,   52,
       35,   35,  362,   52,   66,  319,   52,   79,   56,   56,
       52,   75,   75,   75,   75,   75,   75,   35,   35,   56,
       35,   66,   35,   78,   52,   35,   35,   38,   52,   66,

       78,   52,   80,   56,   56,   52,  350,   38,   61,   67,
       82,   38,   38,   61,   61,   38,   38,   38,   84,   67,
      348,   73,   38,   78,   67,   73,   72,   80,   67,   76,
       91,   76,   38,   61,   67,   82,   38,   38,   61,   61,
       38,   38,   38,   84,   67,   72,   76,   81,   78,   67,
       81,   73,   92,   67,   93,   91,   72,   83,   95,   76,
       76,   94,   83,   94,   96,   83,   95,   99,  100,  101,
       72,   76,   81,  316,  166,   81,   73,   92,  316,   93,
      105,   72,   83,   95,   76,   76,   94,   83,   94,   96,
       83,   95,   99,  100,  101,  106,   76,   87,   87,   87,

       87,   87,   87,  103,  108,  105,  110,  111,  112,  113,
      103,  115,  116,  119,  120,  118,  121,  122,  123,  124,
      106,  110,  127,   98,  118,  118,   97,  128,  103,  108,
      118,  110,  111,  112,  113,  103,  115,  116,  119,  120,
      118,  121,  122,  123,  124,  129,  110,  127,  126,  118,
      118,  126,  128,  130,  132,  118,  133,  134,  126,  135,
      136,  137,  142,  145,  146,  147,  148,  149,  132,   70,
      129,   69,  150,  126,  151,  152,  126,  153,  130,  132,
      154,  133,  134,  126,  135,  136,  137,  142,  145,  146,
      147,  148,  149,  132,  138,  138,  138,  150,  155,  151,

      152,  156,  153,  157,  158,  154,  159,  160,  138,  162,
      167,  138,  138,  138,  138,  138,  138,  138,  158,  138,
      138,  138,  161,  155,   54,  168,  156,   42,  157,  158,
      169,  159,  160,  138,  162,  167,  138,  138,  138,  138,
      138,  138,  138,  158,  163,  163,  163,  163,  163,  163,
      168,  170,  161,  172,  176,  169,  175,  175,  175,  175,
      175,  175,  177,  179,  180,  183,  185,  186,  187,  188,
      190,  191,  192,  189,  193,  194,  170,  161,  172,  176,
      189,  179,  195,  197,  198,  199,  200,  177,  179,  180,
      183,  185,  186,  187,  188,  190,  191,  192,  189,  193,

      194,  201,  202,  203,  204,  189,  179,  195,  197,  198,
      199,  200,  205,  206,  209,  210,  211,  212,  208,  213,
      214,  215,  216,  217,  218,  220,  201,  202,  203,  204,
      208,  221,   17,  227,  236,   13,  238,  205,  206,  209,
      210,  211,  212,  208,  213,  214,  215,  216,  217,  218,
      220,  239,  223,  237,  240,  208,  221,  223,  227,  236,
      237,  238,  241,  242,  243,  244,  245,  246,  247,  248,
      249,  250,  252,  253,  256,  251,  239,  223,  237,  240,
      251,  327,  223,    0,    0,  237,  327,  241,  242,  243,
      244,  245,  246,  247,  248,  249,  250,  252,  253,  256,

      251,  257,  258,  261,  263,  251,  254,  254,  254,  254,
      254,  254,  262,  262,  262,  262,  262,  262,  264,  266,
      268,  268,  268,  268,  269,  270,  257,  258,  261,  263,
      271,  272,  273,  275,  276,  278,  279,  280,  281,  273,
      282,  284,    0,  264,  266,  285,  287,  290,  291,  269,
      270,  292,  293,  294,  295,  271,  272,  296,  275,  276,
      278,  279,  280,  281,  298,  282,  284,  273,  299,  300,
      285,  287,  290,  291,  301,  302,  292,  293,  294,  295,
      303,  304,  296,  305,  306,  307,  308,  310,  309,  298,
      311,  312,  273,  299,  300,  309,  303,  313,    0,  301,

      302,  314,  318,  310,  320,  321,  304,  322,  305,  306,
      307,  308,  323,  324,  325,  311,  312,  326,  329,  331,
      332,  333,  313,  309,  336,  329,  314,  318,  347,  320,
      321,  334,  322,    0,    0,  347,    0,  323,  324,  325,
      336,  337,  326,  338,  331,  332,  333,  343,  309,  328,
      328,  328,  328,  328,  328,  344,  334,  335,  335,  335,
      335,  335,  335,  345,  346,  351,  337,  349,  338,  352,
      353,  354,  343,  356,  349,  357,  359,  360,  361,  363,
      344,  351,  364,  361,  365,  366,  367,  368,  345,  346,
      369,  370,  371,  373,  352,  353,  354,  374,  356,  371,

      357,  359,  360,  375,  363,  376,  377,  364,  378,  365,
      366,  367,  368,  380,  381,  369,  370,  382,  373,  383,
      384,  386,  374,  387,  378,  385,  388,  389,  375,  390,
      376,  377,  385,  391,  392,  393,  394,  395,  380,  381,
      396,  397,  382,    0,  383,  384,  386,  407,  387,  401,
      398,  388,  389,  402,  390,  398,  403,  404,  391,  392,
      393,  394,  395,  407,  408,  396,  397,  400,  400,  400,
      400,  400,  400,  409,  401,  413,  418,  419,  402,  420,
      408,  403,  404,  405,  405,  405,  405,  405,  405,  414,
      416,  413,  417,  421,  422,  420,  414,  416,  409,  417,

      423,  418,  419,  425,  427,  429,  430,  431,  433,  434,
      435,  437,  444,  442,  443,  447,  448,  449,  421,  422,
      442,  443,  445,  450,    0,  423,    0,    0,  425,  427,
      429,  430,  431,  433,  434,  435,  437,  444,  445,  455,
      447,  448,  449,  457,  458,  461,  463,    0,  450,  454,
      454,  454,  454,  454,  454,  459,  459,  459,  459,  459,
      459,  461,  463,  465,  455,  467,  470,  471,  457,  458,
      465,  473,  467,  474,  477,  478,  479,  481,  482,  484,
      488,  487,  500,  471,    0,    0,  501,  492,  493,  474,
      477,  470,    0,  481,    0,    0,  473,  487,  500,    0,

      478,  479,  501,  482,  484,  488,  490,  490,  490,  490,
      490,  490,  492,  493,  494,  494,  494,  494,  494,  494,
      505,  510,  510,  510,  510,  510,  510,  513,  513,  513,
      513,  513,  513,    0,    0,    0,  505,  516,  516,  516,
      516,  516,  516,  517,  517,  517,  517,  517,  517,  518,
      518,  518,  518,  518,  518,  519,  519,  519,  519,  519,
      519,  520,  520,  520,  520,  520,  520,  521,  521,  521,
      521,  521,  521,  522,  522,  522,  522,  522,  522,  523,
      523,  523,  523,  523,  523,  524,  524,  524,  524,  524,
      524,  525,  525,  525,  525,  525,  525,  526,  526,  526,

      526,  526,  526,  527,  527,  527,  527,  527,  527,  528,
      528,  528,  528,  528,  528,  529,  529,  529,  529,  529,
      529,  530,  530,  530,  530,  530,  530,  531,  531,  531,
      531,  531,  531,  532,  532,  532,  532,  532,  532,  533,
      533,  533,  533,  533,  533,  534,  534,  534,  534,  534,
      534,  535,  535,  535,  535,  535,  535,  536,  536,  536,
      536,  536,  536,  537,  537,  537,  537,  537,  537,  538,
      538,  538,  538,  538,  538,  539,  539,  539,  539,  539,
      539,  540,  540,  540,  540,  540,  540,  541,  541,  541,
      541,  541,  541,  542,  542,  542,  542,  542,  542,  543,

      543,  543,  543,  543,  543,  544,  544,  544,  544,  544,
      544,  545,  545,  545,  545,  545,  545,  546,  546,  546,
      546,  546,  546,  547,  547,  547,  547,  547,  547,  548,
      548,  548,  548,  548,  548,  549,  549,  549,  549,  549,
      549,  550,  550,  550,  550,  550,  550,  551,  551,  551,
      551,  551,  551,  552,  552,  552,  552,  552,  552,  553,
      553,  553,  553,  553,  553,  554,  554,  554,  554,  554,
      554,  555,  555,  555,  555,  555,  555,  556,  556,  556,
      556,  556,  556,  557,  557,  557,  557,  557,  557,  558,
      558,  558,  558,  558,  558,  559,  559,  559,  559,  559,

      559,  560,  560,  560,  560,  560,  560,  564,  564,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  563
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 1;

static yyconst flex_int16_t yy_rule_linenum[91] =
    {   0,
      150,  151,  152,  153,  154,  155,  156,  157,  158,  159,
      165,  173,  179,  189,  190,  191,  192,  193,  194,  195,
      196,  197,  198,  199,  200,  201,  202,  203,  204,  205,
      206,  207,  209,  210,  211,  212,  213,  214,  215,  216,
      218,  219,  220,  221,  222,  223,  224,  225,  226,  227,
      228,  229,  230,  231,  232,  233,  234,  235,  237,  238,
      239,  240,  241,  242,  243,  244,  247,  248,  249,  250,
      253,  254,  255,  256,  257,  258,  260,  261,  263,  264,
      265,  266,  267,  269,  271,  274,  279,  280,  281,  282
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "..\\..\\scanner.l"
/*
    Copyright (C) 2016-2021 Sauro Menna
    Copyright (C) 2009 Cedric ISSALY
 *
 *	This file is part of GCSORT.
 *
 *  GCSORT is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  GCSORT is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with GCSORT.  If not, see <http://www.gnu.org/licenses/>.
  
*/
#line 22 "..\\..\\scanner.l"
  #include <stdio.h>
  #include <stdlib.h>
  #ifndef _MSC_VER
	  #define _strdup strdup
	  #include "utils.h"
	  #define xstrtoll   strtoll
  #else
	  #include <io.h>
	  #define isatty _isatty
	  #define fileno _fileno
	  #define xstrtoll    _strtoi64
  #endif
  #include "gcsort.h"
  #include "parser.h"
  char * pEnd;
  int    nPhase = 0;
  extern char szMexToken[260];

  void yyerror(const char *error) {
	printf("Error : %s\n",error);
	if(yytext != NULL) {
		printf("Error near element : %s\n", yytext);
		printf("Token  : %s\n", szMexToken);
	}
} 
#define YY_NO_INPUT
/* for position and length */
/* for value, example condition */
/* sign for numeric values */
/* string */
/* Separator Date/Time */
/* File type */
/*  Format Type Field   */
/* CH|BI|FI|FL|PD|ZD|TI|OT|CTO|LI|OL|CLO|CST|LS|CSL */
/*  CH  Char            
BI  Unsigned Binary
FI  Signed Binary
Fl  Floating Point
PD  Packed
LI / OL / CLO Signed Numeric - sign lealing 
CST Signed Numeric - trailing separate sign
LS / CSL Signed Numeric - leading separate sign
FS / CSF Signed Numeric - with optional leading floating sign  (PIC +++9, PIC ----,...)
*/
/* FORMATTYPE	 CH|BI|FI|FL|PD|ZD|CLO|CST|CSL */
/* extended FORMATTYPE	 CH|BI|FI|FL|PD|ZD|TI|OT|CTO|LI|OL|CLO|CST|LS|CSL */
/* released FORMATTYPE	 CH|BI|FI|FL|PD|ZD|CLO|CST|CSL */
/*
DataType	Len	Type
Y2T		8	ZD Y2T8 = Y4T8 (?) C'ccyymmdd' or Z'ccyymmdd'     
Y2T		4	ZD Y2T4 : C'yyxx' or Z'yyxx' 
Y2T		2	ZD Y2T2 'yy'
Y2T		3	ZD Y2T2 'yyx'
Y2T		5	ZD 5,Y2T: C'yyddd' or Z'yyddd'
Y2T		6	ZD 6,Y2T: C'yymmdd' or Z'yymmdd'     
Y4T		7	ZD 7,Y4T: C'ccyyddd' or Z'ccyyddd'    
Y2B		1	BI
Y2C		2	ZD
Y2D		1	PD
Y2P		2	PD
Y2S		2	ZD
Y2U		3	PD  P'yyddd'   
Y2V		4	PD  P'yymmdd'    
Y2X		3	PD  P'dddyy'    
Y2Y		4	PD  P'mmddyy'
Y2Z		2	ZD
*/
/*  Char Type  for condition CharType = C(char) | X(hexdical) <String>    */
/* prec CHARTCOND       C|X  */
/*  Char Type  CharType = C(char) | X(hexdical) |Z(zero binary) <String>    */
/*  Order A = Ascending, D = Descending */
/*  Key Tye for indexed file P=Primary, A= ALternative, AD = Alternative with duplicates, C = Continue */
/* Fixed record */
/* Variable record */
/* comment for occursfill */ 
/* ntimes X,Z,C */
/* Operator condition */ 
/* Joinkeys File */
/* OCCURFILL   [0-9]{1,5}[C|X|Z]{1} */
/* <CHSC>{CHARTYPE} */
/* <ORDK>{ORDER} */
/* <KEYV>{KEYTYPE} */
/* Num +/- for date */
/* ADDSUBNUM   [0-9]{1,3}          */





#line 1193 "..\\..\\scanner.c"

#define INITIAL 0
#define KEYV 1
#define ORDK 2
#define CHSC 3
#define TCOND 4
#define TORG 5

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */

static int yy_init_globals (void );

/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* %if-bison-bridge */
/* %endif */

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

/* %not-for-header */

/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */

/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\
/* %if-c++-only C++ definition \ */\
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
/* %endif */
/* %if-c++-only */
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */

/* %ok-for-header */

/* %not-for-header */

/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */

extern int yylex (void);

#define YY_DECL int yylex (void)
/* %endif */
/* %if-c++-only C++ definition */
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %not-for-header */

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
/* %% [7.0] user's declarations go here */
#line 148 "..\\..\\scanner.l"


#line 1429 "..\\..\\scanner.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
/* %if-c-only */
			yyin = stdin;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! yyout )
/* %if-c-only */
			yyout = stdout;
/* %endif */
/* %if-c++-only */
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 564 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 563 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 91 )
				fprintf( stderr, "--accepting rule at line %ld (\"%s\")\n",
				         (long)yy_rule_linenum[yy_act], yytext );
			else if ( yy_act == 91 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         yytext );
			else if ( yy_act == 92 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 150 "..\\..\\scanner.l"
return BUILD;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 151 "..\\..\\scanner.l"
return CHANGE;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 152 "..\\..\\scanner.l"
return FILL;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 153 "..\\..\\scanner.l"
return NOMATCH;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 154 "..\\..\\scanner.l"
BEGIN(TCOND);   return COND; 
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 155 "..\\..\\scanner.l"
return COPY; 
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 156 "..\\..\\scanner.l"
return COPY; 
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 157 "..\\..\\scanner.l"
return TOKSKIP;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 158 "..\\..\\scanner.l"
return ENDREC;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 159 "..\\..\\scanner.l"
if (nPhase == 1) { 
                                BEGIN(ORDK);  
                                nPhase = 0; 
                            }else {	
                                BEGIN(CHSC); 
                            } return FIELDS; 
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 165 "..\\..\\scanner.l"
if (nPhase == 1) { 
                                BEGIN(ORDK);  
                                nPhase = 0; 
                            }else {	
                                BEGIN(CHSC); 
                           } return FIELDS; 
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 173 "..\\..\\scanner.l"
if (nPhase == 1) {       
                                BEGIN(ORDK);          
                                nPhase = 0;           
                            }else {	                  
                                BEGIN(CHSC);          
                            } return OVERLAY;         
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 179 "..\\..\\scanner.l"
if (nPhase == 1) {       
                                BEGIN(ORDK);          
                                nPhase = 0;           
                            }else {	                  
                                BEGIN(CHSC);          
                           } return OVERLAY;          
	YY_BREAK
/* {SIGN}{ADDSUBNUM}	            yylval.number = strtol(yytext, &pEnd, 10) ;			return ADDSUBNUM; */
case 14:
YY_RULE_SETUP
#line 189 "..\\..\\scanner.l"
return DATE1;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 190 "..\\..\\scanner.l"
return DATE2;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 191 "..\\..\\scanner.l"
return DATE3;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 192 "..\\..\\scanner.l"
return DATE4;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 193 "..\\..\\scanner.l"
return FNAMES; /*   return FILE;   */
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 194 "..\\..\\scanner.l"
return FNAMES; /*   return FILES;   */
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 195 "..\\..\\scanner.l"
return FNAMES;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 196 "..\\..\\scanner.l"
return FORMAT;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 197 "..\\..\\scanner.l"
BEGIN(INITIAL); return GIVE;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 198 "..\\..\\scanner.l"
BEGIN(TCOND);   return INCLUDE; 
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 199 "..\\..\\scanner.l"
BEGIN(CHSC);    return INREC;		
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 200 "..\\..\\scanner.l"
BEGIN(CHSC);    return OUTREC;		
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 201 "..\\..\\scanner.l"
BEGIN(KEYV);    return KEY;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 202 "..\\..\\scanner.l"
return LENGTH;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 203 "..\\..\\scanner.l"
nPhase = 1;  BEGIN(INITIAL); return MERGE;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 204 "..\\..\\scanner.l"
nPhase = 1;  BEGIN(INITIAL); return JOINKEYS;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 205 "..\\..\\scanner.l"
return NONE;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 206 "..\\..\\scanner.l"
BEGIN(TCOND);   return OMIT; 
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 207 "..\\..\\scanner.l"
return OPTION;
	YY_BREAK
/*"ORG"		                                    return ORG;*/
case 33:
YY_RULE_SETUP
#line 209 "..\\..\\scanner.l"
BEGIN(TORG);                return ORG;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 210 "..\\..\\scanner.l"
return OUTFIL;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 211 "..\\..\\scanner.l"
return OUTFIL;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 212 "..\\..\\scanner.l"
BEGIN(CHSC);    return OUTREC;		
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 213 "..\\..\\scanner.l"
return SAVE;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 214 "..\\..\\scanner.l"
return SKIPREC;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 215 "..\\..\\scanner.l"
return EXROUT;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 216 "..\\..\\scanner.l"
return MODS;
	YY_BREAK
/* "RECORD"	                         return RECORD; */
case 41:
YY_RULE_SETUP
#line 218 "..\\..\\scanner.l"
BEGIN(INITIAL); return RECORD;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 219 "..\\..\\scanner.l"
nPhase = 1;  BEGIN(INITIAL); return SORT;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 220 "..\\..\\scanner.l"
return SORTED;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 221 "..\\..\\scanner.l"
return NOSEQCK;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 222 "..\\..\\scanner.l"
return UNPAIRED;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 223 "..\\..\\scanner.l"
return ONLY;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 224 "..\\..\\scanner.l"
return JOIN;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 225 "..\\..\\scanner.l"
BEGIN(CHSC);    return JOINREFORMAT;	
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 226 "..\\..\\scanner.l"
return STARTREC;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 227 "..\\..\\scanner.l"
return STOPAFT;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 228 "..\\..\\scanner.l"
return SPLIT;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 229 "..\\..\\scanner.l"
return SPLITBY;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 230 "..\\..\\scanner.l"
return SUM;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 231 "..\\..\\scanner.l"
return TYPE;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 232 "..\\..\\scanner.l"
BEGIN(INITIAL); return USE;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 233 "..\\..\\scanner.l"
return VLSCMP;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 234 "..\\..\\scanner.l"
return VLSHRT;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 235 "..\\..\\scanner.l"
return Y2PAST;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 237 "..\\..\\scanner.l"
printf("GCSORT - Warning - Token skipped : "); ECHO; printf("\n"); /* return TOKSKIP;  */
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 238 "..\\..\\scanner.l"
printf("GCSORT - Warning - Token skipped : "); ECHO; printf("\n"); /* return TOKSKIP;  */
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 239 "..\\..\\scanner.l"
printf("GCSORT - Warning - Token skipped : "); ECHO; printf("\n"); /* return TOKSKIP;  */
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 240 "..\\..\\scanner.l"
printf("GCSORT - Warning - Token skipped : "); ECHO; printf("\n"); /* return TOKSKIP;  */
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 241 "..\\..\\scanner.l"
printf("GCSORT - Warning - Token skipped : "); ECHO; printf("\n"); /* return TOKSKIP;  */
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 242 "..\\..\\scanner.l"
printf("GCSORT - Warning - Token skipped : "); ECHO; printf("\n"); /* return TOKSKIP;  */
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 243 "..\\..\\scanner.l"
printf("GCSORT - Warning - Token skipped : "); ECHO; printf("\n"); /* return TOKSKIP;  */
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 244 "..\\..\\scanner.l"
printf("GCSORT - Warning - Token skipped : "); ECHO; printf("\n"); /* return TOKSKIP;  */
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 247 "..\\..\\scanner.l"
return AND;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 248 "..\\..\\scanner.l"
return AND;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 249 "..\\..\\scanner.l"
return OR;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 250 "..\\..\\scanner.l"
return OR;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 253 "..\\..\\scanner.l"
yylval.string = _strdup(yytext) ;					return OPCOND; 	
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 254 "..\\..\\scanner.l"
yylval.string = _strdup(yytext) ;					return ORDER; 
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 255 "..\\..\\scanner.l"
yylval.number = strtol(yytext, &pEnd, 10) ;			return DIGIT;  
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 256 "..\\..\\scanner.l"
yylval.number = strtol(yytext, &pEnd, 10) ;			return DIGIT; 
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 257 "..\\..\\scanner.l"
yylval.llnumber = xstrtoll(yytext, &pEnd, 10) ;		return SIGNDIGITBIG;  
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 258 "..\\..\\scanner.l"
yylval.llnumber = xstrtoll(yytext, &pEnd, 10) ;		return SIGNDIGITBIG;  
	YY_BREAK
/* {FORMATTYPE}		        yylval.string = _strdup(yytext) ;                   return FORMATTYPE;  */
case 77:
YY_RULE_SETUP
#line 260 "..\\..\\scanner.l"
yylval.string = _strdup(yytext) ;                   return RECTYPEFIX;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 261 "..\\..\\scanner.l"
yylval.string = _strdup(yytext) ;                   return RECTYPEVAR;
	YY_BREAK
/* {FILETYPE}   	            yylval.string = _strdup(yytext) ;                   return FILETYPE;  */ 
case 79:
YY_RULE_SETUP
#line 263 "..\\..\\scanner.l"
yylval.string = _strdup(yytext) ;                   return FILETYPE; 
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 264 "..\\..\\scanner.l"
yylval.string = _strdup(yytext) ;                   return OCCURFILL;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 265 "..\\..\\scanner.l"
yylval.string = _strdup(yytext) ;                   return CHARTCOND;    
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 266 "..\\..\\scanner.l"
yylval.string = _strdup(yytext) ;                   return CHARTYPE; 
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 267 "..\\..\\scanner.l"
yylval.string = _strdup(yytext) ;					return JOINFILE;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 269 "..\\..\\scanner.l"
yylval.string = _strdup(yytext) ;                   return FORMATTYPE;  
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 271 "..\\..\\scanner.l"
yylval.string = _strdup(yytext) ;					return EXROUT; 	
	YY_BREAK
/* String C''';'   */
case 86:
/* rule 86 can match eol */
YY_RULE_SETUP
#line 274 "..\\..\\scanner.l"
{yylval.string=malloc(strlen(yytext)-1);
					 memcpy(yylval.string,yytext+1,strlen(yytext)-2);
					 yylval.string[strlen(yytext)-2]=0;
					 return STRING;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 279 "..\\..\\scanner.l"
yylval.string = _strdup(yytext) ; return KEYTYPE; 
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 280 "..\\..\\scanner.l"
yylval.string = _strdup(yytext) ; return STRING;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 281 "..\\..\\scanner.l"

	YY_BREAK
case 90:
YY_RULE_SETUP
#line 282 "..\\..\\scanner.l"
return yytext[0];
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 285 "..\\..\\scanner.l"
ECHO;
	YY_BREAK
#line 2024 "..\\..\\scanner.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(KEYV):
case YY_STATE_EOF(ORDK):
case YY_STATE_EOF(CHSC):
case YY_STATE_EOF(TCOND):
case YY_STATE_EOF(TORG):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */

/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
static int yy_get_next_buffer (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */

    static yy_state_type yy_get_previous_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 564 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	register int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 564 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 563);

		return yy_is_jam ? 0 : yy_current_state;
}

/* %if-c-only */

/* %endif */

/* %if-c-only */
#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

/* %endif */
/* %if-c++-only */
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and yylineno */

	return c;
}
/* %if-c-only */
#endif	/* ifndef YY_NO_INPUT */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
    void yyrestart  (FILE * input_file )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
static void yy_load_buffer_state  (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
/* %endif */
/* %if-c++-only */
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
/* %if-c-only */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )
/* %endif */
/* %if-c++-only */
/* %endif */

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
/* %endif */
/* %if-c++-only */
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
void yypop_buffer_state (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
static void yyensure_buffer_stack (void)
/* %endif */
/* %if-c++-only */
/* %endif */
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}
/* %endif */

/* %if-c-only */
/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}
/* %endif */

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}
/* %endif */
/* %if-c++-only */
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/* %if-reentrant */
/* %endif */

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

/* %if-reentrant */
/* %endif */
    return 0;
}
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 285 "..\\..\\scanner.l"


