      Function DBSTATUS
      Function DBOPEN
      Function DBCLOSE
      Function DBCOMPILE
      Function DBEXECUTE
      Function DBRELEASE
      Function DBRESET
      Function DBSQL
      Function DBGET
      Function DBINFO
      Function DBERRMSG
