      Function DBOPEN
      Function DBCLOSE
      Function DBCOMPILE
      Function DBEXECUTE
      Function DBRELEASE
      Function DBRESET
      Function DBSQL
      Function DBGETSTR
      Function DBGETINT
      Function DBSTATUS
      Function DBINFO
      Function DBERRMSG
