# for cygwin
# htdocs=/srv/www/htdocs
htdocs=/var/www/vhosts/wortfee.net/httpdocs

all:	p001_wortfee_html

p001_wortfee_html:
# html
	cp p001_wortfee_datenschutzerklaerung.html $(htdocs)/p001_wortfee_datenschutzerklaerung.html
	cp p001_wortfee_impressum.html $(htdocs)/p001_wortfee_impressum.html
	cp p001_wortfee_index.html $(htdocs)/index.html
	
clean:
# html
	rm -f $(htdocs)/p001_wortfee_datenschutzerklaerung.html
	rm -f $(htdocs)/p001_wortfee_impressum.html
	rm -f $(htdocs)/index.html
    